// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NtfyConfigsColumns holds the columns for the "ntfy_configs" table.
	NtfyConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "server_url", Type: field.TypeString, Default: "https://ntfy.sh"},
		{Name: "topic", Type: field.TypeString, Default: ""},
		{Name: "token", Type: field.TypeString, Default: ""},
		{Name: "on_template", Type: field.TypeString, Default: "{{.Name}} 任务执行成功，灯已开启"},
		{Name: "off_template", Type: field.TypeString, Default: "{{.Name}} 任务执行成功，灯已关闭"},
	}
	// NtfyConfigsTable holds the schema information for the "ntfy_configs" table.
	NtfyConfigsTable = &schema.Table{
		Name:       "ntfy_configs",
		Columns:    NtfyConfigsColumns,
		PrimaryKey: []*schema.Column{NtfyConfigsColumns[0]},
	}
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "creator", Type: field.TypeString},
		{Name: "week_days", Type: field.TypeJSON},
		{Name: "hour", Type: field.TypeInt},
		{Name: "minute", Type: field.TypeInt},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"on", "off", "shutdown", "reboot"}, Default: "on"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "allow_edit_by_others", Type: field.TypeBool},
		{Name: "notify_via_server_chan", Type: field.TypeBool, Default: false},
		{Name: "notify_via_lzc", Type: field.TypeBool, Default: false},
		{Name: "notify_via_ntfy", Type: field.TypeBool, Default: false},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
	}
	// ServerChanConfigsColumns holds the columns for the "server_chan_configs" table.
	ServerChanConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "send_key", Type: field.TypeString},
		{Name: "on_template", Type: field.TypeString, Default: "{{.Name}} 任务执行成功，灯已开启"},
		{Name: "off_template", Type: field.TypeString, Default: "{{.Name}} 任务执行成功，灯已关闭"},
		{Name: "enabled", Type: field.TypeBool, Default: false},
	}
	// ServerChanConfigsTable holds the schema information for the "server_chan_configs" table.
	ServerChanConfigsTable = &schema.Table{
		Name:       "server_chan_configs",
		Columns:    ServerChanConfigsColumns,
		PrimaryKey: []*schema.Column{ServerChanConfigsColumns[0]},
	}
	// UserPreferencesColumns holds the columns for the "user_preferences" table.
	UserPreferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "bulb_style", Type: field.TypeString, Default: "classic"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserPreferencesTable holds the schema information for the "user_preferences" table.
	UserPreferencesTable = &schema.Table{
		Name:       "user_preferences",
		Columns:    UserPreferencesColumns,
		PrimaryKey: []*schema.Column{UserPreferencesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userpreference_user_id",
				Unique:  true,
				Columns: []*schema.Column{UserPreferencesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NtfyConfigsTable,
		SchedulesTable,
		ServerChanConfigsTable,
		UserPreferencesTable,
	}
)

func init() {
}
