// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "creator", Type: field.TypeString},
		{Name: "week_days", Type: field.TypeJSON},
		{Name: "hour", Type: field.TypeInt},
		{Name: "minute", Type: field.TypeInt},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"on", "off"}, Default: "on"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "allow_edit_by_others", Type: field.TypeBool},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SchedulesTable,
	}
)

func init() {
}
