// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/predicate"
	"cat-led/internal/ent/schedule"
	"cat-led/internal/ent/serverchanconfig"
	"cat-led/internal/ent/userpreference"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSchedule         = "Schedule"
	TypeServerChanConfig = "ServerChanConfig"
	TypeUserPreference   = "UserPreference"
)

// ScheduleMutation represents an operation that mutates the Schedule nodes in the graph.
type ScheduleMutation struct {
	config
	op                     Op
	typ                    string
	id                     *uuid.UUID
	name                   *string
	creator                *string
	week_days              *[]int
	appendweek_days        []int
	hour                   *int
	addhour                *int
	minute                 *int
	addminute              *int
	operation              *schedule.Operation
	enabled                *bool
	allow_edit_by_others   *bool
	notify_via_server_chan *bool
	notify_via_lzc         *bool
	clearedFields          map[string]struct{}
	done                   bool
	oldValue               func(context.Context) (*Schedule, error)
	predicates             []predicate.Schedule
}

var _ ent.Mutation = (*ScheduleMutation)(nil)

// scheduleOption allows management of the mutation configuration using functional options.
type scheduleOption func(*ScheduleMutation)

// newScheduleMutation creates new mutation for the Schedule entity.
func newScheduleMutation(c config, op Op, opts ...scheduleOption) *ScheduleMutation {
	m := &ScheduleMutation{
		config:        c,
		op:            op,
		typ:           TypeSchedule,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withScheduleID sets the ID field of the mutation.
func withScheduleID(id uuid.UUID) scheduleOption {
	return func(m *ScheduleMutation) {
		var (
			err   error
			once  sync.Once
			value *Schedule
		)
		m.oldValue = func(ctx context.Context) (*Schedule, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Schedule.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSchedule sets the old Schedule of the mutation.
func withSchedule(node *Schedule) scheduleOption {
	return func(m *ScheduleMutation) {
		m.oldValue = func(context.Context) (*Schedule, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ScheduleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ScheduleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Schedule entities.
func (m *ScheduleMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ScheduleMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ScheduleMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Schedule.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ScheduleMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ScheduleMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ScheduleMutation) ResetName() {
	m.name = nil
}

// SetCreator sets the "creator" field.
func (m *ScheduleMutation) SetCreator(s string) {
	m.creator = &s
}

// Creator returns the value of the "creator" field in the mutation.
func (m *ScheduleMutation) Creator() (r string, exists bool) {
	v := m.creator
	if v == nil {
		return
	}
	return *v, true
}

// OldCreator returns the old "creator" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldCreator(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreator is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreator requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreator: %w", err)
	}
	return oldValue.Creator, nil
}

// ResetCreator resets all changes to the "creator" field.
func (m *ScheduleMutation) ResetCreator() {
	m.creator = nil
}

// SetWeekDays sets the "week_days" field.
func (m *ScheduleMutation) SetWeekDays(i []int) {
	m.week_days = &i
	m.appendweek_days = nil
}

// WeekDays returns the value of the "week_days" field in the mutation.
func (m *ScheduleMutation) WeekDays() (r []int, exists bool) {
	v := m.week_days
	if v == nil {
		return
	}
	return *v, true
}

// OldWeekDays returns the old "week_days" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldWeekDays(ctx context.Context) (v []int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWeekDays is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWeekDays requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWeekDays: %w", err)
	}
	return oldValue.WeekDays, nil
}

// AppendWeekDays adds i to the "week_days" field.
func (m *ScheduleMutation) AppendWeekDays(i []int) {
	m.appendweek_days = append(m.appendweek_days, i...)
}

// AppendedWeekDays returns the list of values that were appended to the "week_days" field in this mutation.
func (m *ScheduleMutation) AppendedWeekDays() ([]int, bool) {
	if len(m.appendweek_days) == 0 {
		return nil, false
	}
	return m.appendweek_days, true
}

// ResetWeekDays resets all changes to the "week_days" field.
func (m *ScheduleMutation) ResetWeekDays() {
	m.week_days = nil
	m.appendweek_days = nil
}

// SetHour sets the "hour" field.
func (m *ScheduleMutation) SetHour(i int) {
	m.hour = &i
	m.addhour = nil
}

// Hour returns the value of the "hour" field in the mutation.
func (m *ScheduleMutation) Hour() (r int, exists bool) {
	v := m.hour
	if v == nil {
		return
	}
	return *v, true
}

// OldHour returns the old "hour" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldHour(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHour is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHour requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHour: %w", err)
	}
	return oldValue.Hour, nil
}

// AddHour adds i to the "hour" field.
func (m *ScheduleMutation) AddHour(i int) {
	if m.addhour != nil {
		*m.addhour += i
	} else {
		m.addhour = &i
	}
}

// AddedHour returns the value that was added to the "hour" field in this mutation.
func (m *ScheduleMutation) AddedHour() (r int, exists bool) {
	v := m.addhour
	if v == nil {
		return
	}
	return *v, true
}

// ResetHour resets all changes to the "hour" field.
func (m *ScheduleMutation) ResetHour() {
	m.hour = nil
	m.addhour = nil
}

// SetMinute sets the "minute" field.
func (m *ScheduleMutation) SetMinute(i int) {
	m.minute = &i
	m.addminute = nil
}

// Minute returns the value of the "minute" field in the mutation.
func (m *ScheduleMutation) Minute() (r int, exists bool) {
	v := m.minute
	if v == nil {
		return
	}
	return *v, true
}

// OldMinute returns the old "minute" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldMinute(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMinute is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMinute requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinute: %w", err)
	}
	return oldValue.Minute, nil
}

// AddMinute adds i to the "minute" field.
func (m *ScheduleMutation) AddMinute(i int) {
	if m.addminute != nil {
		*m.addminute += i
	} else {
		m.addminute = &i
	}
}

// AddedMinute returns the value that was added to the "minute" field in this mutation.
func (m *ScheduleMutation) AddedMinute() (r int, exists bool) {
	v := m.addminute
	if v == nil {
		return
	}
	return *v, true
}

// ResetMinute resets all changes to the "minute" field.
func (m *ScheduleMutation) ResetMinute() {
	m.minute = nil
	m.addminute = nil
}

// SetOperation sets the "operation" field.
func (m *ScheduleMutation) SetOperation(s schedule.Operation) {
	m.operation = &s
}

// Operation returns the value of the "operation" field in the mutation.
func (m *ScheduleMutation) Operation() (r schedule.Operation, exists bool) {
	v := m.operation
	if v == nil {
		return
	}
	return *v, true
}

// OldOperation returns the old "operation" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldOperation(ctx context.Context) (v schedule.Operation, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOperation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOperation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOperation: %w", err)
	}
	return oldValue.Operation, nil
}

// ResetOperation resets all changes to the "operation" field.
func (m *ScheduleMutation) ResetOperation() {
	m.operation = nil
}

// SetEnabled sets the "enabled" field.
func (m *ScheduleMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *ScheduleMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *ScheduleMutation) ResetEnabled() {
	m.enabled = nil
}

// SetAllowEditByOthers sets the "allow_edit_by_others" field.
func (m *ScheduleMutation) SetAllowEditByOthers(b bool) {
	m.allow_edit_by_others = &b
}

// AllowEditByOthers returns the value of the "allow_edit_by_others" field in the mutation.
func (m *ScheduleMutation) AllowEditByOthers() (r bool, exists bool) {
	v := m.allow_edit_by_others
	if v == nil {
		return
	}
	return *v, true
}

// OldAllowEditByOthers returns the old "allow_edit_by_others" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldAllowEditByOthers(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAllowEditByOthers is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAllowEditByOthers requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAllowEditByOthers: %w", err)
	}
	return oldValue.AllowEditByOthers, nil
}

// ResetAllowEditByOthers resets all changes to the "allow_edit_by_others" field.
func (m *ScheduleMutation) ResetAllowEditByOthers() {
	m.allow_edit_by_others = nil
}

// SetNotifyViaServerChan sets the "notify_via_server_chan" field.
func (m *ScheduleMutation) SetNotifyViaServerChan(b bool) {
	m.notify_via_server_chan = &b
}

// NotifyViaServerChan returns the value of the "notify_via_server_chan" field in the mutation.
func (m *ScheduleMutation) NotifyViaServerChan() (r bool, exists bool) {
	v := m.notify_via_server_chan
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifyViaServerChan returns the old "notify_via_server_chan" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldNotifyViaServerChan(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifyViaServerChan is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifyViaServerChan requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifyViaServerChan: %w", err)
	}
	return oldValue.NotifyViaServerChan, nil
}

// ResetNotifyViaServerChan resets all changes to the "notify_via_server_chan" field.
func (m *ScheduleMutation) ResetNotifyViaServerChan() {
	m.notify_via_server_chan = nil
}

// SetNotifyViaLzc sets the "notify_via_lzc" field.
func (m *ScheduleMutation) SetNotifyViaLzc(b bool) {
	m.notify_via_lzc = &b
}

// NotifyViaLzc returns the value of the "notify_via_lzc" field in the mutation.
func (m *ScheduleMutation) NotifyViaLzc() (r bool, exists bool) {
	v := m.notify_via_lzc
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifyViaLzc returns the old "notify_via_lzc" field's value of the Schedule entity.
// If the Schedule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScheduleMutation) OldNotifyViaLzc(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifyViaLzc is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifyViaLzc requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifyViaLzc: %w", err)
	}
	return oldValue.NotifyViaLzc, nil
}

// ResetNotifyViaLzc resets all changes to the "notify_via_lzc" field.
func (m *ScheduleMutation) ResetNotifyViaLzc() {
	m.notify_via_lzc = nil
}

// Where appends a list predicates to the ScheduleMutation builder.
func (m *ScheduleMutation) Where(ps ...predicate.Schedule) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ScheduleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ScheduleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Schedule, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ScheduleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ScheduleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Schedule).
func (m *ScheduleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ScheduleMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.name != nil {
		fields = append(fields, schedule.FieldName)
	}
	if m.creator != nil {
		fields = append(fields, schedule.FieldCreator)
	}
	if m.week_days != nil {
		fields = append(fields, schedule.FieldWeekDays)
	}
	if m.hour != nil {
		fields = append(fields, schedule.FieldHour)
	}
	if m.minute != nil {
		fields = append(fields, schedule.FieldMinute)
	}
	if m.operation != nil {
		fields = append(fields, schedule.FieldOperation)
	}
	if m.enabled != nil {
		fields = append(fields, schedule.FieldEnabled)
	}
	if m.allow_edit_by_others != nil {
		fields = append(fields, schedule.FieldAllowEditByOthers)
	}
	if m.notify_via_server_chan != nil {
		fields = append(fields, schedule.FieldNotifyViaServerChan)
	}
	if m.notify_via_lzc != nil {
		fields = append(fields, schedule.FieldNotifyViaLzc)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ScheduleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case schedule.FieldName:
		return m.Name()
	case schedule.FieldCreator:
		return m.Creator()
	case schedule.FieldWeekDays:
		return m.WeekDays()
	case schedule.FieldHour:
		return m.Hour()
	case schedule.FieldMinute:
		return m.Minute()
	case schedule.FieldOperation:
		return m.Operation()
	case schedule.FieldEnabled:
		return m.Enabled()
	case schedule.FieldAllowEditByOthers:
		return m.AllowEditByOthers()
	case schedule.FieldNotifyViaServerChan:
		return m.NotifyViaServerChan()
	case schedule.FieldNotifyViaLzc:
		return m.NotifyViaLzc()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ScheduleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case schedule.FieldName:
		return m.OldName(ctx)
	case schedule.FieldCreator:
		return m.OldCreator(ctx)
	case schedule.FieldWeekDays:
		return m.OldWeekDays(ctx)
	case schedule.FieldHour:
		return m.OldHour(ctx)
	case schedule.FieldMinute:
		return m.OldMinute(ctx)
	case schedule.FieldOperation:
		return m.OldOperation(ctx)
	case schedule.FieldEnabled:
		return m.OldEnabled(ctx)
	case schedule.FieldAllowEditByOthers:
		return m.OldAllowEditByOthers(ctx)
	case schedule.FieldNotifyViaServerChan:
		return m.OldNotifyViaServerChan(ctx)
	case schedule.FieldNotifyViaLzc:
		return m.OldNotifyViaLzc(ctx)
	}
	return nil, fmt.Errorf("unknown Schedule field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScheduleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case schedule.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case schedule.FieldCreator:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreator(v)
		return nil
	case schedule.FieldWeekDays:
		v, ok := value.([]int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWeekDays(v)
		return nil
	case schedule.FieldHour:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHour(v)
		return nil
	case schedule.FieldMinute:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinute(v)
		return nil
	case schedule.FieldOperation:
		v, ok := value.(schedule.Operation)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOperation(v)
		return nil
	case schedule.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case schedule.FieldAllowEditByOthers:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAllowEditByOthers(v)
		return nil
	case schedule.FieldNotifyViaServerChan:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifyViaServerChan(v)
		return nil
	case schedule.FieldNotifyViaLzc:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifyViaLzc(v)
		return nil
	}
	return fmt.Errorf("unknown Schedule field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ScheduleMutation) AddedFields() []string {
	var fields []string
	if m.addhour != nil {
		fields = append(fields, schedule.FieldHour)
	}
	if m.addminute != nil {
		fields = append(fields, schedule.FieldMinute)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ScheduleMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case schedule.FieldHour:
		return m.AddedHour()
	case schedule.FieldMinute:
		return m.AddedMinute()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScheduleMutation) AddField(name string, value ent.Value) error {
	switch name {
	case schedule.FieldHour:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHour(v)
		return nil
	case schedule.FieldMinute:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMinute(v)
		return nil
	}
	return fmt.Errorf("unknown Schedule numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ScheduleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ScheduleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ScheduleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Schedule nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ScheduleMutation) ResetField(name string) error {
	switch name {
	case schedule.FieldName:
		m.ResetName()
		return nil
	case schedule.FieldCreator:
		m.ResetCreator()
		return nil
	case schedule.FieldWeekDays:
		m.ResetWeekDays()
		return nil
	case schedule.FieldHour:
		m.ResetHour()
		return nil
	case schedule.FieldMinute:
		m.ResetMinute()
		return nil
	case schedule.FieldOperation:
		m.ResetOperation()
		return nil
	case schedule.FieldEnabled:
		m.ResetEnabled()
		return nil
	case schedule.FieldAllowEditByOthers:
		m.ResetAllowEditByOthers()
		return nil
	case schedule.FieldNotifyViaServerChan:
		m.ResetNotifyViaServerChan()
		return nil
	case schedule.FieldNotifyViaLzc:
		m.ResetNotifyViaLzc()
		return nil
	}
	return fmt.Errorf("unknown Schedule field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ScheduleMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ScheduleMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ScheduleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ScheduleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ScheduleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ScheduleMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ScheduleMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Schedule unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ScheduleMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Schedule edge %s", name)
}

// ServerChanConfigMutation represents an operation that mutates the ServerChanConfig nodes in the graph.
type ServerChanConfigMutation struct {
	config
	op            Op
	typ           string
	id            *int
	send_key      *string
	on_template   *string
	off_template  *string
	enabled       *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ServerChanConfig, error)
	predicates    []predicate.ServerChanConfig
}

var _ ent.Mutation = (*ServerChanConfigMutation)(nil)

// serverchanconfigOption allows management of the mutation configuration using functional options.
type serverchanconfigOption func(*ServerChanConfigMutation)

// newServerChanConfigMutation creates new mutation for the ServerChanConfig entity.
func newServerChanConfigMutation(c config, op Op, opts ...serverchanconfigOption) *ServerChanConfigMutation {
	m := &ServerChanConfigMutation{
		config:        c,
		op:            op,
		typ:           TypeServerChanConfig,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withServerChanConfigID sets the ID field of the mutation.
func withServerChanConfigID(id int) serverchanconfigOption {
	return func(m *ServerChanConfigMutation) {
		var (
			err   error
			once  sync.Once
			value *ServerChanConfig
		)
		m.oldValue = func(ctx context.Context) (*ServerChanConfig, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ServerChanConfig.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withServerChanConfig sets the old ServerChanConfig of the mutation.
func withServerChanConfig(node *ServerChanConfig) serverchanconfigOption {
	return func(m *ServerChanConfigMutation) {
		m.oldValue = func(context.Context) (*ServerChanConfig, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ServerChanConfigMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ServerChanConfigMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ServerChanConfigMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ServerChanConfigMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ServerChanConfig.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSendKey sets the "send_key" field.
func (m *ServerChanConfigMutation) SetSendKey(s string) {
	m.send_key = &s
}

// SendKey returns the value of the "send_key" field in the mutation.
func (m *ServerChanConfigMutation) SendKey() (r string, exists bool) {
	v := m.send_key
	if v == nil {
		return
	}
	return *v, true
}

// OldSendKey returns the old "send_key" field's value of the ServerChanConfig entity.
// If the ServerChanConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerChanConfigMutation) OldSendKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSendKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSendKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSendKey: %w", err)
	}
	return oldValue.SendKey, nil
}

// ResetSendKey resets all changes to the "send_key" field.
func (m *ServerChanConfigMutation) ResetSendKey() {
	m.send_key = nil
}

// SetOnTemplate sets the "on_template" field.
func (m *ServerChanConfigMutation) SetOnTemplate(s string) {
	m.on_template = &s
}

// OnTemplate returns the value of the "on_template" field in the mutation.
func (m *ServerChanConfigMutation) OnTemplate() (r string, exists bool) {
	v := m.on_template
	if v == nil {
		return
	}
	return *v, true
}

// OldOnTemplate returns the old "on_template" field's value of the ServerChanConfig entity.
// If the ServerChanConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerChanConfigMutation) OldOnTemplate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOnTemplate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOnTemplate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOnTemplate: %w", err)
	}
	return oldValue.OnTemplate, nil
}

// ResetOnTemplate resets all changes to the "on_template" field.
func (m *ServerChanConfigMutation) ResetOnTemplate() {
	m.on_template = nil
}

// SetOffTemplate sets the "off_template" field.
func (m *ServerChanConfigMutation) SetOffTemplate(s string) {
	m.off_template = &s
}

// OffTemplate returns the value of the "off_template" field in the mutation.
func (m *ServerChanConfigMutation) OffTemplate() (r string, exists bool) {
	v := m.off_template
	if v == nil {
		return
	}
	return *v, true
}

// OldOffTemplate returns the old "off_template" field's value of the ServerChanConfig entity.
// If the ServerChanConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerChanConfigMutation) OldOffTemplate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOffTemplate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOffTemplate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOffTemplate: %w", err)
	}
	return oldValue.OffTemplate, nil
}

// ResetOffTemplate resets all changes to the "off_template" field.
func (m *ServerChanConfigMutation) ResetOffTemplate() {
	m.off_template = nil
}

// SetEnabled sets the "enabled" field.
func (m *ServerChanConfigMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *ServerChanConfigMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the ServerChanConfig entity.
// If the ServerChanConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerChanConfigMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *ServerChanConfigMutation) ResetEnabled() {
	m.enabled = nil
}

// Where appends a list predicates to the ServerChanConfigMutation builder.
func (m *ServerChanConfigMutation) Where(ps ...predicate.ServerChanConfig) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ServerChanConfigMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ServerChanConfigMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ServerChanConfig, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ServerChanConfigMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ServerChanConfigMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ServerChanConfig).
func (m *ServerChanConfigMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ServerChanConfigMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.send_key != nil {
		fields = append(fields, serverchanconfig.FieldSendKey)
	}
	if m.on_template != nil {
		fields = append(fields, serverchanconfig.FieldOnTemplate)
	}
	if m.off_template != nil {
		fields = append(fields, serverchanconfig.FieldOffTemplate)
	}
	if m.enabled != nil {
		fields = append(fields, serverchanconfig.FieldEnabled)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ServerChanConfigMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case serverchanconfig.FieldSendKey:
		return m.SendKey()
	case serverchanconfig.FieldOnTemplate:
		return m.OnTemplate()
	case serverchanconfig.FieldOffTemplate:
		return m.OffTemplate()
	case serverchanconfig.FieldEnabled:
		return m.Enabled()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ServerChanConfigMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case serverchanconfig.FieldSendKey:
		return m.OldSendKey(ctx)
	case serverchanconfig.FieldOnTemplate:
		return m.OldOnTemplate(ctx)
	case serverchanconfig.FieldOffTemplate:
		return m.OldOffTemplate(ctx)
	case serverchanconfig.FieldEnabled:
		return m.OldEnabled(ctx)
	}
	return nil, fmt.Errorf("unknown ServerChanConfig field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ServerChanConfigMutation) SetField(name string, value ent.Value) error {
	switch name {
	case serverchanconfig.FieldSendKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSendKey(v)
		return nil
	case serverchanconfig.FieldOnTemplate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOnTemplate(v)
		return nil
	case serverchanconfig.FieldOffTemplate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOffTemplate(v)
		return nil
	case serverchanconfig.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	}
	return fmt.Errorf("unknown ServerChanConfig field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ServerChanConfigMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ServerChanConfigMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ServerChanConfigMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ServerChanConfig numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ServerChanConfigMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ServerChanConfigMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ServerChanConfigMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ServerChanConfig nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ServerChanConfigMutation) ResetField(name string) error {
	switch name {
	case serverchanconfig.FieldSendKey:
		m.ResetSendKey()
		return nil
	case serverchanconfig.FieldOnTemplate:
		m.ResetOnTemplate()
		return nil
	case serverchanconfig.FieldOffTemplate:
		m.ResetOffTemplate()
		return nil
	case serverchanconfig.FieldEnabled:
		m.ResetEnabled()
		return nil
	}
	return fmt.Errorf("unknown ServerChanConfig field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ServerChanConfigMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ServerChanConfigMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ServerChanConfigMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ServerChanConfigMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ServerChanConfigMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ServerChanConfigMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ServerChanConfigMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ServerChanConfig unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ServerChanConfigMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ServerChanConfig edge %s", name)
}

// UserPreferenceMutation represents an operation that mutates the UserPreference nodes in the graph.
type UserPreferenceMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user_id       *string
	bulb_style    *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UserPreference, error)
	predicates    []predicate.UserPreference
}

var _ ent.Mutation = (*UserPreferenceMutation)(nil)

// userpreferenceOption allows management of the mutation configuration using functional options.
type userpreferenceOption func(*UserPreferenceMutation)

// newUserPreferenceMutation creates new mutation for the UserPreference entity.
func newUserPreferenceMutation(c config, op Op, opts ...userpreferenceOption) *UserPreferenceMutation {
	m := &UserPreferenceMutation{
		config:        c,
		op:            op,
		typ:           TypeUserPreference,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserPreferenceID sets the ID field of the mutation.
func withUserPreferenceID(id int) userpreferenceOption {
	return func(m *UserPreferenceMutation) {
		var (
			err   error
			once  sync.Once
			value *UserPreference
		)
		m.oldValue = func(ctx context.Context) (*UserPreference, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserPreference.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserPreference sets the old UserPreference of the mutation.
func withUserPreference(node *UserPreference) userpreferenceOption {
	return func(m *UserPreferenceMutation) {
		m.oldValue = func(context.Context) (*UserPreference, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserPreferenceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserPreferenceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserPreferenceMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserPreferenceMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserPreference.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *UserPreferenceMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserPreferenceMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserPreference entity.
// If the UserPreference object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserPreferenceMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserPreferenceMutation) ResetUserID() {
	m.user_id = nil
}

// SetBulbStyle sets the "bulb_style" field.
func (m *UserPreferenceMutation) SetBulbStyle(s string) {
	m.bulb_style = &s
}

// BulbStyle returns the value of the "bulb_style" field in the mutation.
func (m *UserPreferenceMutation) BulbStyle() (r string, exists bool) {
	v := m.bulb_style
	if v == nil {
		return
	}
	return *v, true
}

// OldBulbStyle returns the old "bulb_style" field's value of the UserPreference entity.
// If the UserPreference object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserPreferenceMutation) OldBulbStyle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBulbStyle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBulbStyle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBulbStyle: %w", err)
	}
	return oldValue.BulbStyle, nil
}

// ResetBulbStyle resets all changes to the "bulb_style" field.
func (m *UserPreferenceMutation) ResetBulbStyle() {
	m.bulb_style = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserPreferenceMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserPreferenceMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the UserPreference entity.
// If the UserPreference object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserPreferenceMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserPreferenceMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserPreferenceMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserPreferenceMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the UserPreference entity.
// If the UserPreference object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserPreferenceMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserPreferenceMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the UserPreferenceMutation builder.
func (m *UserPreferenceMutation) Where(ps ...predicate.UserPreference) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserPreferenceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserPreferenceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserPreference, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserPreferenceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserPreferenceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserPreference).
func (m *UserPreferenceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserPreferenceMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.user_id != nil {
		fields = append(fields, userpreference.FieldUserID)
	}
	if m.bulb_style != nil {
		fields = append(fields, userpreference.FieldBulbStyle)
	}
	if m.created_at != nil {
		fields = append(fields, userpreference.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, userpreference.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserPreferenceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case userpreference.FieldUserID:
		return m.UserID()
	case userpreference.FieldBulbStyle:
		return m.BulbStyle()
	case userpreference.FieldCreatedAt:
		return m.CreatedAt()
	case userpreference.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserPreferenceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case userpreference.FieldUserID:
		return m.OldUserID(ctx)
	case userpreference.FieldBulbStyle:
		return m.OldBulbStyle(ctx)
	case userpreference.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case userpreference.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown UserPreference field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserPreferenceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case userpreference.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case userpreference.FieldBulbStyle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBulbStyle(v)
		return nil
	case userpreference.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case userpreference.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown UserPreference field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserPreferenceMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserPreferenceMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserPreferenceMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UserPreference numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserPreferenceMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserPreferenceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserPreferenceMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserPreference nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserPreferenceMutation) ResetField(name string) error {
	switch name {
	case userpreference.FieldUserID:
		m.ResetUserID()
		return nil
	case userpreference.FieldBulbStyle:
		m.ResetBulbStyle()
		return nil
	case userpreference.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case userpreference.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown UserPreference field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserPreferenceMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserPreferenceMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserPreferenceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserPreferenceMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserPreferenceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserPreferenceMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserPreferenceMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UserPreference unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserPreferenceMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UserPreference edge %s", name)
}
