// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/ntfyconfig"
	"cat-led/internal/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NtfyConfigUpdate is the builder for updating NtfyConfig entities.
type NtfyConfigUpdate struct {
	config
	hooks    []Hook
	mutation *NtfyConfigMutation
}

// Where appends a list predicates to the NtfyConfigUpdate builder.
func (_u *NtfyConfigUpdate) Where(ps ...predicate.NtfyConfig) *NtfyConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NtfyConfigUpdate) SetEnabled(v bool) *NtfyConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NtfyConfigUpdate) SetNillableEnabled(v *bool) *NtfyConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetServerURL sets the "server_url" field.
func (_u *NtfyConfigUpdate) SetServerURL(v string) *NtfyConfigUpdate {
	_u.mutation.SetServerURL(v)
	return _u
}

// SetNillableServerURL sets the "server_url" field if the given value is not nil.
func (_u *NtfyConfigUpdate) SetNillableServerURL(v *string) *NtfyConfigUpdate {
	if v != nil {
		_u.SetServerURL(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *NtfyConfigUpdate) SetTopic(v string) *NtfyConfigUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *NtfyConfigUpdate) SetNillableTopic(v *string) *NtfyConfigUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *NtfyConfigUpdate) SetToken(v string) *NtfyConfigUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *NtfyConfigUpdate) SetNillableToken(v *string) *NtfyConfigUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetOnTemplate sets the "on_template" field.
func (_u *NtfyConfigUpdate) SetOnTemplate(v string) *NtfyConfigUpdate {
	_u.mutation.SetOnTemplate(v)
	return _u
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (_u *NtfyConfigUpdate) SetNillableOnTemplate(v *string) *NtfyConfigUpdate {
	if v != nil {
		_u.SetOnTemplate(*v)
	}
	return _u
}

// SetOffTemplate sets the "off_template" field.
func (_u *NtfyConfigUpdate) SetOffTemplate(v string) *NtfyConfigUpdate {
	_u.mutation.SetOffTemplate(v)
	return _u
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (_u *NtfyConfigUpdate) SetNillableOffTemplate(v *string) *NtfyConfigUpdate {
	if v != nil {
		_u.SetOffTemplate(*v)
	}
	return _u
}

// Mutation returns the NtfyConfigMutation object of the builder.
func (_u *NtfyConfigUpdate) Mutation() *NtfyConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NtfyConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NtfyConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NtfyConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NtfyConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NtfyConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ntfyconfig.Table, ntfyconfig.Columns, sqlgraph.NewFieldSpec(ntfyconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ntfyconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ServerURL(); ok {
		_spec.SetField(ntfyconfig.FieldServerURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(ntfyconfig.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(ntfyconfig.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnTemplate(); ok {
		_spec.SetField(ntfyconfig.FieldOnTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.OffTemplate(); ok {
		_spec.SetField(ntfyconfig.FieldOffTemplate, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ntfyconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NtfyConfigUpdateOne is the builder for updating a single NtfyConfig entity.
type NtfyConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NtfyConfigMutation
}

// SetEnabled sets the "enabled" field.
func (_u *NtfyConfigUpdateOne) SetEnabled(v bool) *NtfyConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NtfyConfigUpdateOne) SetNillableEnabled(v *bool) *NtfyConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetServerURL sets the "server_url" field.
func (_u *NtfyConfigUpdateOne) SetServerURL(v string) *NtfyConfigUpdateOne {
	_u.mutation.SetServerURL(v)
	return _u
}

// SetNillableServerURL sets the "server_url" field if the given value is not nil.
func (_u *NtfyConfigUpdateOne) SetNillableServerURL(v *string) *NtfyConfigUpdateOne {
	if v != nil {
		_u.SetServerURL(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *NtfyConfigUpdateOne) SetTopic(v string) *NtfyConfigUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *NtfyConfigUpdateOne) SetNillableTopic(v *string) *NtfyConfigUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *NtfyConfigUpdateOne) SetToken(v string) *NtfyConfigUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *NtfyConfigUpdateOne) SetNillableToken(v *string) *NtfyConfigUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetOnTemplate sets the "on_template" field.
func (_u *NtfyConfigUpdateOne) SetOnTemplate(v string) *NtfyConfigUpdateOne {
	_u.mutation.SetOnTemplate(v)
	return _u
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (_u *NtfyConfigUpdateOne) SetNillableOnTemplate(v *string) *NtfyConfigUpdateOne {
	if v != nil {
		_u.SetOnTemplate(*v)
	}
	return _u
}

// SetOffTemplate sets the "off_template" field.
func (_u *NtfyConfigUpdateOne) SetOffTemplate(v string) *NtfyConfigUpdateOne {
	_u.mutation.SetOffTemplate(v)
	return _u
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (_u *NtfyConfigUpdateOne) SetNillableOffTemplate(v *string) *NtfyConfigUpdateOne {
	if v != nil {
		_u.SetOffTemplate(*v)
	}
	return _u
}

// Mutation returns the NtfyConfigMutation object of the builder.
func (_u *NtfyConfigUpdateOne) Mutation() *NtfyConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the NtfyConfigUpdate builder.
func (_u *NtfyConfigUpdateOne) Where(ps ...predicate.NtfyConfig) *NtfyConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NtfyConfigUpdateOne) Select(field string, fields ...string) *NtfyConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NtfyConfig entity.
func (_u *NtfyConfigUpdateOne) Save(ctx context.Context) (*NtfyConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NtfyConfigUpdateOne) SaveX(ctx context.Context) *NtfyConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NtfyConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NtfyConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NtfyConfigUpdateOne) sqlSave(ctx context.Context) (_node *NtfyConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(ntfyconfig.Table, ntfyconfig.Columns, sqlgraph.NewFieldSpec(ntfyconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NtfyConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ntfyconfig.FieldID)
		for _, f := range fields {
			if !ntfyconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ntfyconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ntfyconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ServerURL(); ok {
		_spec.SetField(ntfyconfig.FieldServerURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(ntfyconfig.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(ntfyconfig.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnTemplate(); ok {
		_spec.SetField(ntfyconfig.FieldOnTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.OffTemplate(); ok {
		_spec.SetField(ntfyconfig.FieldOffTemplate, field.TypeString, value)
	}
	_node = &NtfyConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ntfyconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
