// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/ntfyconfig"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// NtfyConfig is the model entity for the NtfyConfig schema.
type NtfyConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 是否启用ntfy通知
	Enabled bool `json:"enabled,omitempty"`
	// ntfy服务器地址
	ServerURL string `json:"server_url,omitempty"`
	// ntfy主题/topic
	Topic string `json:"topic,omitempty"`
	// ntfy访问令牌(可选)
	Token string `json:"token,omitempty"`
	// 开灯通知模板
	OnTemplate string `json:"on_template,omitempty"`
	// 关灯通知模板
	OffTemplate  string `json:"off_template,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NtfyConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ntfyconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case ntfyconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case ntfyconfig.FieldServerURL, ntfyconfig.FieldTopic, ntfyconfig.FieldToken, ntfyconfig.FieldOnTemplate, ntfyconfig.FieldOffTemplate:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NtfyConfig fields.
func (_m *NtfyConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ntfyconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ntfyconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case ntfyconfig.FieldServerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_url", values[i])
			} else if value.Valid {
				_m.ServerURL = value.String
			}
		case ntfyconfig.FieldTopic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic", values[i])
			} else if value.Valid {
				_m.Topic = value.String
			}
		case ntfyconfig.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case ntfyconfig.FieldOnTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field on_template", values[i])
			} else if value.Valid {
				_m.OnTemplate = value.String
			}
		case ntfyconfig.FieldOffTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field off_template", values[i])
			} else if value.Valid {
				_m.OffTemplate = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NtfyConfig.
// This includes values selected through modifiers, order, etc.
func (_m *NtfyConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NtfyConfig.
// Note that you need to call NtfyConfig.Unwrap() before calling this method if this NtfyConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NtfyConfig) Update() *NtfyConfigUpdateOne {
	return NewNtfyConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NtfyConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NtfyConfig) Unwrap() *NtfyConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NtfyConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NtfyConfig) String() string {
	var builder strings.Builder
	builder.WriteString("NtfyConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("server_url=")
	builder.WriteString(_m.ServerURL)
	builder.WriteString(", ")
	builder.WriteString("topic=")
	builder.WriteString(_m.Topic)
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("on_template=")
	builder.WriteString(_m.OnTemplate)
	builder.WriteString(", ")
	builder.WriteString("off_template=")
	builder.WriteString(_m.OffTemplate)
	builder.WriteByte(')')
	return builder.String()
}

// NtfyConfigs is a parsable slice of NtfyConfig.
type NtfyConfigs []*NtfyConfig
