// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/ntfyconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NtfyConfigCreate is the builder for creating a NtfyConfig entity.
type NtfyConfigCreate struct {
	config
	mutation *NtfyConfigMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (_c *NtfyConfigCreate) SetEnabled(v bool) *NtfyConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NtfyConfigCreate) SetNillableEnabled(v *bool) *NtfyConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetServerURL sets the "server_url" field.
func (_c *NtfyConfigCreate) SetServerURL(v string) *NtfyConfigCreate {
	_c.mutation.SetServerURL(v)
	return _c
}

// SetNillableServerURL sets the "server_url" field if the given value is not nil.
func (_c *NtfyConfigCreate) SetNillableServerURL(v *string) *NtfyConfigCreate {
	if v != nil {
		_c.SetServerURL(*v)
	}
	return _c
}

// SetTopic sets the "topic" field.
func (_c *NtfyConfigCreate) SetTopic(v string) *NtfyConfigCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_c *NtfyConfigCreate) SetNillableTopic(v *string) *NtfyConfigCreate {
	if v != nil {
		_c.SetTopic(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *NtfyConfigCreate) SetToken(v string) *NtfyConfigCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_c *NtfyConfigCreate) SetNillableToken(v *string) *NtfyConfigCreate {
	if v != nil {
		_c.SetToken(*v)
	}
	return _c
}

// SetOnTemplate sets the "on_template" field.
func (_c *NtfyConfigCreate) SetOnTemplate(v string) *NtfyConfigCreate {
	_c.mutation.SetOnTemplate(v)
	return _c
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (_c *NtfyConfigCreate) SetNillableOnTemplate(v *string) *NtfyConfigCreate {
	if v != nil {
		_c.SetOnTemplate(*v)
	}
	return _c
}

// SetOffTemplate sets the "off_template" field.
func (_c *NtfyConfigCreate) SetOffTemplate(v string) *NtfyConfigCreate {
	_c.mutation.SetOffTemplate(v)
	return _c
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (_c *NtfyConfigCreate) SetNillableOffTemplate(v *string) *NtfyConfigCreate {
	if v != nil {
		_c.SetOffTemplate(*v)
	}
	return _c
}

// Mutation returns the NtfyConfigMutation object of the builder.
func (_c *NtfyConfigCreate) Mutation() *NtfyConfigMutation {
	return _c.mutation
}

// Save creates the NtfyConfig in the database.
func (_c *NtfyConfigCreate) Save(ctx context.Context) (*NtfyConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NtfyConfigCreate) SaveX(ctx context.Context) *NtfyConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NtfyConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NtfyConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NtfyConfigCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ntfyconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ServerURL(); !ok {
		v := ntfyconfig.DefaultServerURL
		_c.mutation.SetServerURL(v)
	}
	if _, ok := _c.mutation.Topic(); !ok {
		v := ntfyconfig.DefaultTopic
		_c.mutation.SetTopic(v)
	}
	if _, ok := _c.mutation.Token(); !ok {
		v := ntfyconfig.DefaultToken
		_c.mutation.SetToken(v)
	}
	if _, ok := _c.mutation.OnTemplate(); !ok {
		v := ntfyconfig.DefaultOnTemplate
		_c.mutation.SetOnTemplate(v)
	}
	if _, ok := _c.mutation.OffTemplate(); !ok {
		v := ntfyconfig.DefaultOffTemplate
		_c.mutation.SetOffTemplate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NtfyConfigCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NtfyConfig.enabled"`)}
	}
	if _, ok := _c.mutation.ServerURL(); !ok {
		return &ValidationError{Name: "server_url", err: errors.New(`ent: missing required field "NtfyConfig.server_url"`)}
	}
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "NtfyConfig.topic"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "NtfyConfig.token"`)}
	}
	if _, ok := _c.mutation.OnTemplate(); !ok {
		return &ValidationError{Name: "on_template", err: errors.New(`ent: missing required field "NtfyConfig.on_template"`)}
	}
	if _, ok := _c.mutation.OffTemplate(); !ok {
		return &ValidationError{Name: "off_template", err: errors.New(`ent: missing required field "NtfyConfig.off_template"`)}
	}
	return nil
}

func (_c *NtfyConfigCreate) sqlSave(ctx context.Context) (*NtfyConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NtfyConfigCreate) createSpec() (*NtfyConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &NtfyConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ntfyconfig.Table, sqlgraph.NewFieldSpec(ntfyconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ntfyconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ServerURL(); ok {
		_spec.SetField(ntfyconfig.FieldServerURL, field.TypeString, value)
		_node.ServerURL = value
	}
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(ntfyconfig.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(ntfyconfig.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.OnTemplate(); ok {
		_spec.SetField(ntfyconfig.FieldOnTemplate, field.TypeString, value)
		_node.OnTemplate = value
	}
	if value, ok := _c.mutation.OffTemplate(); ok {
		_spec.SetField(ntfyconfig.FieldOffTemplate, field.TypeString, value)
		_node.OffTemplate = value
	}
	return _node, _spec
}

// NtfyConfigCreateBulk is the builder for creating many NtfyConfig entities in bulk.
type NtfyConfigCreateBulk struct {
	config
	err      error
	builders []*NtfyConfigCreate
}

// Save creates the NtfyConfig entities in the database.
func (_c *NtfyConfigCreateBulk) Save(ctx context.Context) ([]*NtfyConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NtfyConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NtfyConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NtfyConfigCreateBulk) SaveX(ctx context.Context) []*NtfyConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NtfyConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NtfyConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
