// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/schedule"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ScheduleCreate is the builder for creating a Schedule entity.
type ScheduleCreate struct {
	config
	mutation *ScheduleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ScheduleCreate) SetName(v string) *ScheduleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCreator sets the "creator" field.
func (_c *ScheduleCreate) SetCreator(v string) *ScheduleCreate {
	_c.mutation.SetCreator(v)
	return _c
}

// SetWeekDays sets the "week_days" field.
func (_c *ScheduleCreate) SetWeekDays(v []int) *ScheduleCreate {
	_c.mutation.SetWeekDays(v)
	return _c
}

// SetHour sets the "hour" field.
func (_c *ScheduleCreate) SetHour(v int) *ScheduleCreate {
	_c.mutation.SetHour(v)
	return _c
}

// SetMinute sets the "minute" field.
func (_c *ScheduleCreate) SetMinute(v int) *ScheduleCreate {
	_c.mutation.SetMinute(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *ScheduleCreate) SetOperation(v schedule.Operation) *ScheduleCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableOperation(v *schedule.Operation) *ScheduleCreate {
	if v != nil {
		_c.SetOperation(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ScheduleCreate) SetEnabled(v bool) *ScheduleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableEnabled(v *bool) *ScheduleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetAllowEditByOthers sets the "allow_edit_by_others" field.
func (_c *ScheduleCreate) SetAllowEditByOthers(v bool) *ScheduleCreate {
	_c.mutation.SetAllowEditByOthers(v)
	return _c
}

// SetNotifyViaServerChan sets the "notify_via_server_chan" field.
func (_c *ScheduleCreate) SetNotifyViaServerChan(v bool) *ScheduleCreate {
	_c.mutation.SetNotifyViaServerChan(v)
	return _c
}

// SetNillableNotifyViaServerChan sets the "notify_via_server_chan" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableNotifyViaServerChan(v *bool) *ScheduleCreate {
	if v != nil {
		_c.SetNotifyViaServerChan(*v)
	}
	return _c
}

// SetNotifyViaLzc sets the "notify_via_lzc" field.
func (_c *ScheduleCreate) SetNotifyViaLzc(v bool) *ScheduleCreate {
	_c.mutation.SetNotifyViaLzc(v)
	return _c
}

// SetNillableNotifyViaLzc sets the "notify_via_lzc" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableNotifyViaLzc(v *bool) *ScheduleCreate {
	if v != nil {
		_c.SetNotifyViaLzc(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScheduleCreate) SetID(v uuid.UUID) *ScheduleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableID(v *uuid.UUID) *ScheduleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ScheduleMutation object of the builder.
func (_c *ScheduleCreate) Mutation() *ScheduleMutation {
	return _c.mutation
}

// Save creates the Schedule in the database.
func (_c *ScheduleCreate) Save(ctx context.Context) (*Schedule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduleCreate) SaveX(ctx context.Context) *Schedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduleCreate) defaults() {
	if _, ok := _c.mutation.Operation(); !ok {
		v := schedule.DefaultOperation
		_c.mutation.SetOperation(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := schedule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.NotifyViaServerChan(); !ok {
		v := schedule.DefaultNotifyViaServerChan
		_c.mutation.SetNotifyViaServerChan(v)
	}
	if _, ok := _c.mutation.NotifyViaLzc(); !ok {
		v := schedule.DefaultNotifyViaLzc
		_c.mutation.SetNotifyViaLzc(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := schedule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Schedule.name"`)}
	}
	if _, ok := _c.mutation.Creator(); !ok {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required field "Schedule.creator"`)}
	}
	if _, ok := _c.mutation.WeekDays(); !ok {
		return &ValidationError{Name: "week_days", err: errors.New(`ent: missing required field "Schedule.week_days"`)}
	}
	if _, ok := _c.mutation.Hour(); !ok {
		return &ValidationError{Name: "hour", err: errors.New(`ent: missing required field "Schedule.hour"`)}
	}
	if _, ok := _c.mutation.Minute(); !ok {
		return &ValidationError{Name: "minute", err: errors.New(`ent: missing required field "Schedule.minute"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "Schedule.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := schedule.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Schedule.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Schedule.enabled"`)}
	}
	if _, ok := _c.mutation.AllowEditByOthers(); !ok {
		return &ValidationError{Name: "allow_edit_by_others", err: errors.New(`ent: missing required field "Schedule.allow_edit_by_others"`)}
	}
	if _, ok := _c.mutation.NotifyViaServerChan(); !ok {
		return &ValidationError{Name: "notify_via_server_chan", err: errors.New(`ent: missing required field "Schedule.notify_via_server_chan"`)}
	}
	if _, ok := _c.mutation.NotifyViaLzc(); !ok {
		return &ValidationError{Name: "notify_via_lzc", err: errors.New(`ent: missing required field "Schedule.notify_via_lzc"`)}
	}
	return nil
}

func (_c *ScheduleCreate) sqlSave(ctx context.Context) (*Schedule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduleCreate) createSpec() (*Schedule, *sqlgraph.CreateSpec) {
	var (
		_node = &Schedule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedule.Table, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(schedule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Creator(); ok {
		_spec.SetField(schedule.FieldCreator, field.TypeString, value)
		_node.Creator = value
	}
	if value, ok := _c.mutation.WeekDays(); ok {
		_spec.SetField(schedule.FieldWeekDays, field.TypeJSON, value)
		_node.WeekDays = value
	}
	if value, ok := _c.mutation.Hour(); ok {
		_spec.SetField(schedule.FieldHour, field.TypeInt, value)
		_node.Hour = value
	}
	if value, ok := _c.mutation.Minute(); ok {
		_spec.SetField(schedule.FieldMinute, field.TypeInt, value)
		_node.Minute = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(schedule.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(schedule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.AllowEditByOthers(); ok {
		_spec.SetField(schedule.FieldAllowEditByOthers, field.TypeBool, value)
		_node.AllowEditByOthers = value
	}
	if value, ok := _c.mutation.NotifyViaServerChan(); ok {
		_spec.SetField(schedule.FieldNotifyViaServerChan, field.TypeBool, value)
		_node.NotifyViaServerChan = value
	}
	if value, ok := _c.mutation.NotifyViaLzc(); ok {
		_spec.SetField(schedule.FieldNotifyViaLzc, field.TypeBool, value)
		_node.NotifyViaLzc = value
	}
	return _node, _spec
}

// ScheduleCreateBulk is the builder for creating many Schedule entities in bulk.
type ScheduleCreateBulk struct {
	config
	err      error
	builders []*ScheduleCreate
}

// Save creates the Schedule entities in the database.
func (_c *ScheduleCreateBulk) Save(ctx context.Context) ([]*Schedule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Schedule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduleCreateBulk) SaveX(ctx context.Context) []*Schedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
