// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/predicate"
	"cat-led/internal/ent/schedule"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ScheduleUpdate is the builder for updating Schedule entities.
type ScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleMutation
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (_u *ScheduleUpdate) Where(ps ...predicate.Schedule) *ScheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ScheduleUpdate) SetName(v string) *ScheduleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableName(v *string) *ScheduleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWeekDays sets the "week_days" field.
func (_u *ScheduleUpdate) SetWeekDays(v []int) *ScheduleUpdate {
	_u.mutation.SetWeekDays(v)
	return _u
}

// AppendWeekDays appends value to the "week_days" field.
func (_u *ScheduleUpdate) AppendWeekDays(v []int) *ScheduleUpdate {
	_u.mutation.AppendWeekDays(v)
	return _u
}

// SetHour sets the "hour" field.
func (_u *ScheduleUpdate) SetHour(v int) *ScheduleUpdate {
	_u.mutation.ResetHour()
	_u.mutation.SetHour(v)
	return _u
}

// SetNillableHour sets the "hour" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableHour(v *int) *ScheduleUpdate {
	if v != nil {
		_u.SetHour(*v)
	}
	return _u
}

// AddHour adds value to the "hour" field.
func (_u *ScheduleUpdate) AddHour(v int) *ScheduleUpdate {
	_u.mutation.AddHour(v)
	return _u
}

// SetMinute sets the "minute" field.
func (_u *ScheduleUpdate) SetMinute(v int) *ScheduleUpdate {
	_u.mutation.ResetMinute()
	_u.mutation.SetMinute(v)
	return _u
}

// SetNillableMinute sets the "minute" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableMinute(v *int) *ScheduleUpdate {
	if v != nil {
		_u.SetMinute(*v)
	}
	return _u
}

// AddMinute adds value to the "minute" field.
func (_u *ScheduleUpdate) AddMinute(v int) *ScheduleUpdate {
	_u.mutation.AddMinute(v)
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ScheduleUpdate) SetOperation(v schedule.Operation) *ScheduleUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableOperation(v *schedule.Operation) *ScheduleUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ScheduleUpdate) SetEnabled(v bool) *ScheduleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableEnabled(v *bool) *ScheduleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAllowEditByOthers sets the "allow_edit_by_others" field.
func (_u *ScheduleUpdate) SetAllowEditByOthers(v bool) *ScheduleUpdate {
	_u.mutation.SetAllowEditByOthers(v)
	return _u
}

// SetNillableAllowEditByOthers sets the "allow_edit_by_others" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableAllowEditByOthers(v *bool) *ScheduleUpdate {
	if v != nil {
		_u.SetAllowEditByOthers(*v)
	}
	return _u
}

// SetNotifyViaServerChan sets the "notify_via_server_chan" field.
func (_u *ScheduleUpdate) SetNotifyViaServerChan(v bool) *ScheduleUpdate {
	_u.mutation.SetNotifyViaServerChan(v)
	return _u
}

// SetNillableNotifyViaServerChan sets the "notify_via_server_chan" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableNotifyViaServerChan(v *bool) *ScheduleUpdate {
	if v != nil {
		_u.SetNotifyViaServerChan(*v)
	}
	return _u
}

// SetNotifyViaLzc sets the "notify_via_lzc" field.
func (_u *ScheduleUpdate) SetNotifyViaLzc(v bool) *ScheduleUpdate {
	_u.mutation.SetNotifyViaLzc(v)
	return _u
}

// SetNillableNotifyViaLzc sets the "notify_via_lzc" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableNotifyViaLzc(v *bool) *ScheduleUpdate {
	if v != nil {
		_u.SetNotifyViaLzc(*v)
	}
	return _u
}

// SetNotifyViaNtfy sets the "notify_via_ntfy" field.
func (_u *ScheduleUpdate) SetNotifyViaNtfy(v bool) *ScheduleUpdate {
	_u.mutation.SetNotifyViaNtfy(v)
	return _u
}

// SetNillableNotifyViaNtfy sets the "notify_via_ntfy" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableNotifyViaNtfy(v *bool) *ScheduleUpdate {
	if v != nil {
		_u.SetNotifyViaNtfy(*v)
	}
	return _u
}

// Mutation returns the ScheduleMutation object of the builder.
func (_u *ScheduleUpdate) Mutation() *ScheduleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleUpdate) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := schedule.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Schedule.operation": %w`, err)}
		}
	}
	return nil
}

func (_u *ScheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.WeekDays(); ok {
		_spec.SetField(schedule.FieldWeekDays, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWeekDays(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schedule.FieldWeekDays, value)
		})
	}
	if value, ok := _u.mutation.Hour(); ok {
		_spec.SetField(schedule.FieldHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHour(); ok {
		_spec.AddField(schedule.FieldHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Minute(); ok {
		_spec.SetField(schedule.FieldMinute, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinute(); ok {
		_spec.AddField(schedule.FieldMinute, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(schedule.FieldOperation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(schedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowEditByOthers(); ok {
		_spec.SetField(schedule.FieldAllowEditByOthers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyViaServerChan(); ok {
		_spec.SetField(schedule.FieldNotifyViaServerChan, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyViaLzc(); ok {
		_spec.SetField(schedule.FieldNotifyViaLzc, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyViaNtfy(); ok {
		_spec.SetField(schedule.FieldNotifyViaNtfy, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleUpdateOne is the builder for updating a single Schedule entity.
type ScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleMutation
}

// SetName sets the "name" field.
func (_u *ScheduleUpdateOne) SetName(v string) *ScheduleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableName(v *string) *ScheduleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWeekDays sets the "week_days" field.
func (_u *ScheduleUpdateOne) SetWeekDays(v []int) *ScheduleUpdateOne {
	_u.mutation.SetWeekDays(v)
	return _u
}

// AppendWeekDays appends value to the "week_days" field.
func (_u *ScheduleUpdateOne) AppendWeekDays(v []int) *ScheduleUpdateOne {
	_u.mutation.AppendWeekDays(v)
	return _u
}

// SetHour sets the "hour" field.
func (_u *ScheduleUpdateOne) SetHour(v int) *ScheduleUpdateOne {
	_u.mutation.ResetHour()
	_u.mutation.SetHour(v)
	return _u
}

// SetNillableHour sets the "hour" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableHour(v *int) *ScheduleUpdateOne {
	if v != nil {
		_u.SetHour(*v)
	}
	return _u
}

// AddHour adds value to the "hour" field.
func (_u *ScheduleUpdateOne) AddHour(v int) *ScheduleUpdateOne {
	_u.mutation.AddHour(v)
	return _u
}

// SetMinute sets the "minute" field.
func (_u *ScheduleUpdateOne) SetMinute(v int) *ScheduleUpdateOne {
	_u.mutation.ResetMinute()
	_u.mutation.SetMinute(v)
	return _u
}

// SetNillableMinute sets the "minute" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableMinute(v *int) *ScheduleUpdateOne {
	if v != nil {
		_u.SetMinute(*v)
	}
	return _u
}

// AddMinute adds value to the "minute" field.
func (_u *ScheduleUpdateOne) AddMinute(v int) *ScheduleUpdateOne {
	_u.mutation.AddMinute(v)
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ScheduleUpdateOne) SetOperation(v schedule.Operation) *ScheduleUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableOperation(v *schedule.Operation) *ScheduleUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ScheduleUpdateOne) SetEnabled(v bool) *ScheduleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableEnabled(v *bool) *ScheduleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAllowEditByOthers sets the "allow_edit_by_others" field.
func (_u *ScheduleUpdateOne) SetAllowEditByOthers(v bool) *ScheduleUpdateOne {
	_u.mutation.SetAllowEditByOthers(v)
	return _u
}

// SetNillableAllowEditByOthers sets the "allow_edit_by_others" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableAllowEditByOthers(v *bool) *ScheduleUpdateOne {
	if v != nil {
		_u.SetAllowEditByOthers(*v)
	}
	return _u
}

// SetNotifyViaServerChan sets the "notify_via_server_chan" field.
func (_u *ScheduleUpdateOne) SetNotifyViaServerChan(v bool) *ScheduleUpdateOne {
	_u.mutation.SetNotifyViaServerChan(v)
	return _u
}

// SetNillableNotifyViaServerChan sets the "notify_via_server_chan" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableNotifyViaServerChan(v *bool) *ScheduleUpdateOne {
	if v != nil {
		_u.SetNotifyViaServerChan(*v)
	}
	return _u
}

// SetNotifyViaLzc sets the "notify_via_lzc" field.
func (_u *ScheduleUpdateOne) SetNotifyViaLzc(v bool) *ScheduleUpdateOne {
	_u.mutation.SetNotifyViaLzc(v)
	return _u
}

// SetNillableNotifyViaLzc sets the "notify_via_lzc" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableNotifyViaLzc(v *bool) *ScheduleUpdateOne {
	if v != nil {
		_u.SetNotifyViaLzc(*v)
	}
	return _u
}

// SetNotifyViaNtfy sets the "notify_via_ntfy" field.
func (_u *ScheduleUpdateOne) SetNotifyViaNtfy(v bool) *ScheduleUpdateOne {
	_u.mutation.SetNotifyViaNtfy(v)
	return _u
}

// SetNillableNotifyViaNtfy sets the "notify_via_ntfy" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableNotifyViaNtfy(v *bool) *ScheduleUpdateOne {
	if v != nil {
		_u.SetNotifyViaNtfy(*v)
	}
	return _u
}

// Mutation returns the ScheduleMutation object of the builder.
func (_u *ScheduleUpdateOne) Mutation() *ScheduleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (_u *ScheduleUpdateOne) Where(ps ...predicate.Schedule) *ScheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleUpdateOne) Select(field string, fields ...string) *ScheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Schedule entity.
func (_u *ScheduleUpdateOne) Save(ctx context.Context) (*Schedule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleUpdateOne) SaveX(ctx context.Context) *Schedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleUpdateOne) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := schedule.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Schedule.operation": %w`, err)}
		}
	}
	return nil
}

func (_u *ScheduleUpdateOne) sqlSave(ctx context.Context) (_node *Schedule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Schedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedule.FieldID)
		for _, f := range fields {
			if !schedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.WeekDays(); ok {
		_spec.SetField(schedule.FieldWeekDays, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWeekDays(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, schedule.FieldWeekDays, value)
		})
	}
	if value, ok := _u.mutation.Hour(); ok {
		_spec.SetField(schedule.FieldHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHour(); ok {
		_spec.AddField(schedule.FieldHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Minute(); ok {
		_spec.SetField(schedule.FieldMinute, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinute(); ok {
		_spec.AddField(schedule.FieldMinute, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(schedule.FieldOperation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(schedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowEditByOthers(); ok {
		_spec.SetField(schedule.FieldAllowEditByOthers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyViaServerChan(); ok {
		_spec.SetField(schedule.FieldNotifyViaServerChan, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyViaLzc(); ok {
		_spec.SetField(schedule.FieldNotifyViaLzc, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifyViaNtfy(); ok {
		_spec.SetField(schedule.FieldNotifyViaNtfy, field.TypeBool, value)
	}
	_node = &Schedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
