// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/predicate"
	"cat-led/internal/ent/serverchanconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerChanConfigUpdate is the builder for updating ServerChanConfig entities.
type ServerChanConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ServerChanConfigMutation
}

// Where appends a list predicates to the ServerChanConfigUpdate builder.
func (sccu *ServerChanConfigUpdate) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigUpdate {
	sccu.mutation.Where(ps...)
	return sccu
}

// SetSendKey sets the "send_key" field.
func (sccu *ServerChanConfigUpdate) SetSendKey(s string) *ServerChanConfigUpdate {
	sccu.mutation.SetSendKey(s)
	return sccu
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (sccu *ServerChanConfigUpdate) SetNillableSendKey(s *string) *ServerChanConfigUpdate {
	if s != nil {
		sccu.SetSendKey(*s)
	}
	return sccu
}

// SetOnTemplate sets the "on_template" field.
func (sccu *ServerChanConfigUpdate) SetOnTemplate(s string) *ServerChanConfigUpdate {
	sccu.mutation.SetOnTemplate(s)
	return sccu
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (sccu *ServerChanConfigUpdate) SetNillableOnTemplate(s *string) *ServerChanConfigUpdate {
	if s != nil {
		sccu.SetOnTemplate(*s)
	}
	return sccu
}

// SetOffTemplate sets the "off_template" field.
func (sccu *ServerChanConfigUpdate) SetOffTemplate(s string) *ServerChanConfigUpdate {
	sccu.mutation.SetOffTemplate(s)
	return sccu
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (sccu *ServerChanConfigUpdate) SetNillableOffTemplate(s *string) *ServerChanConfigUpdate {
	if s != nil {
		sccu.SetOffTemplate(*s)
	}
	return sccu
}

// SetEnabled sets the "enabled" field.
func (sccu *ServerChanConfigUpdate) SetEnabled(b bool) *ServerChanConfigUpdate {
	sccu.mutation.SetEnabled(b)
	return sccu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (sccu *ServerChanConfigUpdate) SetNillableEnabled(b *bool) *ServerChanConfigUpdate {
	if b != nil {
		sccu.SetEnabled(*b)
	}
	return sccu
}

// Mutation returns the ServerChanConfigMutation object of the builder.
func (sccu *ServerChanConfigUpdate) Mutation() *ServerChanConfigMutation {
	return sccu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sccu *ServerChanConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, sccu.sqlSave, sccu.mutation, sccu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sccu *ServerChanConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := sccu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sccu *ServerChanConfigUpdate) Exec(ctx context.Context) error {
	_, err := sccu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccu *ServerChanConfigUpdate) ExecX(ctx context.Context) {
	if err := sccu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sccu *ServerChanConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(serverchanconfig.Table, serverchanconfig.Columns, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	if ps := sccu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sccu.mutation.SendKey(); ok {
		_spec.SetField(serverchanconfig.FieldSendKey, field.TypeString, value)
	}
	if value, ok := sccu.mutation.OnTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOnTemplate, field.TypeString, value)
	}
	if value, ok := sccu.mutation.OffTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOffTemplate, field.TypeString, value)
	}
	if value, ok := sccu.mutation.Enabled(); ok {
		_spec.SetField(serverchanconfig.FieldEnabled, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sccu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverchanconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sccu.mutation.done = true
	return n, nil
}

// ServerChanConfigUpdateOne is the builder for updating a single ServerChanConfig entity.
type ServerChanConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServerChanConfigMutation
}

// SetSendKey sets the "send_key" field.
func (sccuo *ServerChanConfigUpdateOne) SetSendKey(s string) *ServerChanConfigUpdateOne {
	sccuo.mutation.SetSendKey(s)
	return sccuo
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (sccuo *ServerChanConfigUpdateOne) SetNillableSendKey(s *string) *ServerChanConfigUpdateOne {
	if s != nil {
		sccuo.SetSendKey(*s)
	}
	return sccuo
}

// SetOnTemplate sets the "on_template" field.
func (sccuo *ServerChanConfigUpdateOne) SetOnTemplate(s string) *ServerChanConfigUpdateOne {
	sccuo.mutation.SetOnTemplate(s)
	return sccuo
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (sccuo *ServerChanConfigUpdateOne) SetNillableOnTemplate(s *string) *ServerChanConfigUpdateOne {
	if s != nil {
		sccuo.SetOnTemplate(*s)
	}
	return sccuo
}

// SetOffTemplate sets the "off_template" field.
func (sccuo *ServerChanConfigUpdateOne) SetOffTemplate(s string) *ServerChanConfigUpdateOne {
	sccuo.mutation.SetOffTemplate(s)
	return sccuo
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (sccuo *ServerChanConfigUpdateOne) SetNillableOffTemplate(s *string) *ServerChanConfigUpdateOne {
	if s != nil {
		sccuo.SetOffTemplate(*s)
	}
	return sccuo
}

// SetEnabled sets the "enabled" field.
func (sccuo *ServerChanConfigUpdateOne) SetEnabled(b bool) *ServerChanConfigUpdateOne {
	sccuo.mutation.SetEnabled(b)
	return sccuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (sccuo *ServerChanConfigUpdateOne) SetNillableEnabled(b *bool) *ServerChanConfigUpdateOne {
	if b != nil {
		sccuo.SetEnabled(*b)
	}
	return sccuo
}

// Mutation returns the ServerChanConfigMutation object of the builder.
func (sccuo *ServerChanConfigUpdateOne) Mutation() *ServerChanConfigMutation {
	return sccuo.mutation
}

// Where appends a list predicates to the ServerChanConfigUpdate builder.
func (sccuo *ServerChanConfigUpdateOne) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigUpdateOne {
	sccuo.mutation.Where(ps...)
	return sccuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sccuo *ServerChanConfigUpdateOne) Select(field string, fields ...string) *ServerChanConfigUpdateOne {
	sccuo.fields = append([]string{field}, fields...)
	return sccuo
}

// Save executes the query and returns the updated ServerChanConfig entity.
func (sccuo *ServerChanConfigUpdateOne) Save(ctx context.Context) (*ServerChanConfig, error) {
	return withHooks(ctx, sccuo.sqlSave, sccuo.mutation, sccuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sccuo *ServerChanConfigUpdateOne) SaveX(ctx context.Context) *ServerChanConfig {
	node, err := sccuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sccuo *ServerChanConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := sccuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccuo *ServerChanConfigUpdateOne) ExecX(ctx context.Context) {
	if err := sccuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (sccuo *ServerChanConfigUpdateOne) sqlSave(ctx context.Context) (_node *ServerChanConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(serverchanconfig.Table, serverchanconfig.Columns, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	id, ok := sccuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServerChanConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sccuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serverchanconfig.FieldID)
		for _, f := range fields {
			if !serverchanconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serverchanconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sccuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sccuo.mutation.SendKey(); ok {
		_spec.SetField(serverchanconfig.FieldSendKey, field.TypeString, value)
	}
	if value, ok := sccuo.mutation.OnTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOnTemplate, field.TypeString, value)
	}
	if value, ok := sccuo.mutation.OffTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOffTemplate, field.TypeString, value)
	}
	if value, ok := sccuo.mutation.Enabled(); ok {
		_spec.SetField(serverchanconfig.FieldEnabled, field.TypeBool, value)
	}
	_node = &ServerChanConfig{config: sccuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sccuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverchanconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sccuo.mutation.done = true
	return _node, nil
}
