// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/serverchanconfig"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ServerChanConfig is the model entity for the ServerChanConfig schema.
type ServerChanConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Server酱的SendKey
	SendKey string `json:"send_key,omitempty"`
	// 开灯通知模板
	OnTemplate string `json:"on_template,omitempty"`
	// 关灯通知模板
	OffTemplate string `json:"off_template,omitempty"`
	// 是否启用Server酱通知
	Enabled bool `json:"enabled,omitempty"`
	// 是否启用电子邮件通知
	EmailEnabled bool `json:"email_enabled,omitempty"`
	// 电子邮件通知URL
	EmailURL     string `json:"email_url,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServerChanConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serverchanconfig.FieldEnabled, serverchanconfig.FieldEmailEnabled:
			values[i] = new(sql.NullBool)
		case serverchanconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case serverchanconfig.FieldSendKey, serverchanconfig.FieldOnTemplate, serverchanconfig.FieldOffTemplate, serverchanconfig.FieldEmailURL:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServerChanConfig fields.
func (_m *ServerChanConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serverchanconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case serverchanconfig.FieldSendKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field send_key", values[i])
			} else if value.Valid {
				_m.SendKey = value.String
			}
		case serverchanconfig.FieldOnTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field on_template", values[i])
			} else if value.Valid {
				_m.OnTemplate = value.String
			}
		case serverchanconfig.FieldOffTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field off_template", values[i])
			} else if value.Valid {
				_m.OffTemplate = value.String
			}
		case serverchanconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case serverchanconfig.FieldEmailEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_enabled", values[i])
			} else if value.Valid {
				_m.EmailEnabled = value.Bool
			}
		case serverchanconfig.FieldEmailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_url", values[i])
			} else if value.Valid {
				_m.EmailURL = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServerChanConfig.
// This includes values selected through modifiers, order, etc.
func (_m *ServerChanConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ServerChanConfig.
// Note that you need to call ServerChanConfig.Unwrap() before calling this method if this ServerChanConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServerChanConfig) Update() *ServerChanConfigUpdateOne {
	return NewServerChanConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServerChanConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServerChanConfig) Unwrap() *ServerChanConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServerChanConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServerChanConfig) String() string {
	var builder strings.Builder
	builder.WriteString("ServerChanConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("send_key=")
	builder.WriteString(_m.SendKey)
	builder.WriteString(", ")
	builder.WriteString("on_template=")
	builder.WriteString(_m.OnTemplate)
	builder.WriteString(", ")
	builder.WriteString("off_template=")
	builder.WriteString(_m.OffTemplate)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("email_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmailEnabled))
	builder.WriteString(", ")
	builder.WriteString("email_url=")
	builder.WriteString(_m.EmailURL)
	builder.WriteByte(')')
	return builder.String()
}

// ServerChanConfigs is a parsable slice of ServerChanConfig.
type ServerChanConfigs []*ServerChanConfig
