// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/predicate"
	"cat-led/internal/ent/serverchanconfig"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerChanConfigQuery is the builder for querying ServerChanConfig entities.
type ServerChanConfigQuery struct {
	config
	ctx        *QueryContext
	order      []serverchanconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.ServerChanConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServerChanConfigQuery builder.
func (sccq *ServerChanConfigQuery) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigQuery {
	sccq.predicates = append(sccq.predicates, ps...)
	return sccq
}

// Limit the number of records to be returned by this query.
func (sccq *ServerChanConfigQuery) Limit(limit int) *ServerChanConfigQuery {
	sccq.ctx.Limit = &limit
	return sccq
}

// Offset to start from.
func (sccq *ServerChanConfigQuery) Offset(offset int) *ServerChanConfigQuery {
	sccq.ctx.Offset = &offset
	return sccq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sccq *ServerChanConfigQuery) Unique(unique bool) *ServerChanConfigQuery {
	sccq.ctx.Unique = &unique
	return sccq
}

// Order specifies how the records should be ordered.
func (sccq *ServerChanConfigQuery) Order(o ...serverchanconfig.OrderOption) *ServerChanConfigQuery {
	sccq.order = append(sccq.order, o...)
	return sccq
}

// First returns the first ServerChanConfig entity from the query.
// Returns a *NotFoundError when no ServerChanConfig was found.
func (sccq *ServerChanConfigQuery) First(ctx context.Context) (*ServerChanConfig, error) {
	nodes, err := sccq.Limit(1).All(setContextOp(ctx, sccq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serverchanconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) FirstX(ctx context.Context) *ServerChanConfig {
	node, err := sccq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServerChanConfig ID from the query.
// Returns a *NotFoundError when no ServerChanConfig ID was found.
func (sccq *ServerChanConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sccq.Limit(1).IDs(setContextOp(ctx, sccq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serverchanconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := sccq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServerChanConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServerChanConfig entity is found.
// Returns a *NotFoundError when no ServerChanConfig entities are found.
func (sccq *ServerChanConfigQuery) Only(ctx context.Context) (*ServerChanConfig, error) {
	nodes, err := sccq.Limit(2).All(setContextOp(ctx, sccq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serverchanconfig.Label}
	default:
		return nil, &NotSingularError{serverchanconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) OnlyX(ctx context.Context) *ServerChanConfig {
	node, err := sccq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServerChanConfig ID in the query.
// Returns a *NotSingularError when more than one ServerChanConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (sccq *ServerChanConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sccq.Limit(2).IDs(setContextOp(ctx, sccq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serverchanconfig.Label}
	default:
		err = &NotSingularError{serverchanconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := sccq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServerChanConfigs.
func (sccq *ServerChanConfigQuery) All(ctx context.Context) ([]*ServerChanConfig, error) {
	ctx = setContextOp(ctx, sccq.ctx, ent.OpQueryAll)
	if err := sccq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServerChanConfig, *ServerChanConfigQuery]()
	return withInterceptors[[]*ServerChanConfig](ctx, sccq, qr, sccq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) AllX(ctx context.Context) []*ServerChanConfig {
	nodes, err := sccq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServerChanConfig IDs.
func (sccq *ServerChanConfigQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sccq.ctx.Unique == nil && sccq.path != nil {
		sccq.Unique(true)
	}
	ctx = setContextOp(ctx, sccq.ctx, ent.OpQueryIDs)
	if err = sccq.Select(serverchanconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := sccq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sccq *ServerChanConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sccq.ctx, ent.OpQueryCount)
	if err := sccq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sccq, querierCount[*ServerChanConfigQuery](), sccq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) CountX(ctx context.Context) int {
	count, err := sccq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sccq *ServerChanConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sccq.ctx, ent.OpQueryExist)
	switch _, err := sccq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sccq *ServerChanConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := sccq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServerChanConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sccq *ServerChanConfigQuery) Clone() *ServerChanConfigQuery {
	if sccq == nil {
		return nil
	}
	return &ServerChanConfigQuery{
		config:     sccq.config,
		ctx:        sccq.ctx.Clone(),
		order:      append([]serverchanconfig.OrderOption{}, sccq.order...),
		inters:     append([]Interceptor{}, sccq.inters...),
		predicates: append([]predicate.ServerChanConfig{}, sccq.predicates...),
		// clone intermediate query.
		sql:  sccq.sql.Clone(),
		path: sccq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SendKey string `json:"send_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServerChanConfig.Query().
//		GroupBy(serverchanconfig.FieldSendKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sccq *ServerChanConfigQuery) GroupBy(field string, fields ...string) *ServerChanConfigGroupBy {
	sccq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServerChanConfigGroupBy{build: sccq}
	grbuild.flds = &sccq.ctx.Fields
	grbuild.label = serverchanconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SendKey string `json:"send_key,omitempty"`
//	}
//
//	client.ServerChanConfig.Query().
//		Select(serverchanconfig.FieldSendKey).
//		Scan(ctx, &v)
func (sccq *ServerChanConfigQuery) Select(fields ...string) *ServerChanConfigSelect {
	sccq.ctx.Fields = append(sccq.ctx.Fields, fields...)
	sbuild := &ServerChanConfigSelect{ServerChanConfigQuery: sccq}
	sbuild.label = serverchanconfig.Label
	sbuild.flds, sbuild.scan = &sccq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServerChanConfigSelect configured with the given aggregations.
func (sccq *ServerChanConfigQuery) Aggregate(fns ...AggregateFunc) *ServerChanConfigSelect {
	return sccq.Select().Aggregate(fns...)
}

func (sccq *ServerChanConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sccq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sccq); err != nil {
				return err
			}
		}
	}
	for _, f := range sccq.ctx.Fields {
		if !serverchanconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sccq.path != nil {
		prev, err := sccq.path(ctx)
		if err != nil {
			return err
		}
		sccq.sql = prev
	}
	return nil
}

func (sccq *ServerChanConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServerChanConfig, error) {
	var (
		nodes = []*ServerChanConfig{}
		_spec = sccq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServerChanConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServerChanConfig{config: sccq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sccq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sccq *ServerChanConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sccq.querySpec()
	_spec.Node.Columns = sccq.ctx.Fields
	if len(sccq.ctx.Fields) > 0 {
		_spec.Unique = sccq.ctx.Unique != nil && *sccq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sccq.driver, _spec)
}

func (sccq *ServerChanConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(serverchanconfig.Table, serverchanconfig.Columns, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	_spec.From = sccq.sql
	if unique := sccq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sccq.path != nil {
		_spec.Unique = true
	}
	if fields := sccq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serverchanconfig.FieldID)
		for i := range fields {
			if fields[i] != serverchanconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sccq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sccq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sccq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sccq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sccq *ServerChanConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sccq.driver.Dialect())
	t1 := builder.Table(serverchanconfig.Table)
	columns := sccq.ctx.Fields
	if len(columns) == 0 {
		columns = serverchanconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sccq.sql != nil {
		selector = sccq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sccq.ctx.Unique != nil && *sccq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sccq.predicates {
		p(selector)
	}
	for _, p := range sccq.order {
		p(selector)
	}
	if offset := sccq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sccq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServerChanConfigGroupBy is the group-by builder for ServerChanConfig entities.
type ServerChanConfigGroupBy struct {
	selector
	build *ServerChanConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sccgb *ServerChanConfigGroupBy) Aggregate(fns ...AggregateFunc) *ServerChanConfigGroupBy {
	sccgb.fns = append(sccgb.fns, fns...)
	return sccgb
}

// Scan applies the selector query and scans the result into the given value.
func (sccgb *ServerChanConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sccgb.build.ctx, ent.OpQueryGroupBy)
	if err := sccgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServerChanConfigQuery, *ServerChanConfigGroupBy](ctx, sccgb.build, sccgb, sccgb.build.inters, v)
}

func (sccgb *ServerChanConfigGroupBy) sqlScan(ctx context.Context, root *ServerChanConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sccgb.fns))
	for _, fn := range sccgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sccgb.flds)+len(sccgb.fns))
		for _, f := range *sccgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sccgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sccgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServerChanConfigSelect is the builder for selecting fields of ServerChanConfig entities.
type ServerChanConfigSelect struct {
	*ServerChanConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sccs *ServerChanConfigSelect) Aggregate(fns ...AggregateFunc) *ServerChanConfigSelect {
	sccs.fns = append(sccs.fns, fns...)
	return sccs
}

// Scan applies the selector query and scans the result into the given value.
func (sccs *ServerChanConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sccs.ctx, ent.OpQuerySelect)
	if err := sccs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServerChanConfigQuery, *ServerChanConfigSelect](ctx, sccs.ServerChanConfigQuery, sccs, sccs.inters, v)
}

func (sccs *ServerChanConfigSelect) sqlScan(ctx context.Context, root *ServerChanConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sccs.fns))
	for _, fn := range sccs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sccs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sccs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
