// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/predicate"
	"cat-led/internal/ent/serverchanconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerChanConfigUpdate is the builder for updating ServerChanConfig entities.
type ServerChanConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ServerChanConfigMutation
}

// Where appends a list predicates to the ServerChanConfigUpdate builder.
func (_u *ServerChanConfigUpdate) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSendKey sets the "send_key" field.
func (_u *ServerChanConfigUpdate) SetSendKey(v string) *ServerChanConfigUpdate {
	_u.mutation.SetSendKey(v)
	return _u
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (_u *ServerChanConfigUpdate) SetNillableSendKey(v *string) *ServerChanConfigUpdate {
	if v != nil {
		_u.SetSendKey(*v)
	}
	return _u
}

// SetOnTemplate sets the "on_template" field.
func (_u *ServerChanConfigUpdate) SetOnTemplate(v string) *ServerChanConfigUpdate {
	_u.mutation.SetOnTemplate(v)
	return _u
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (_u *ServerChanConfigUpdate) SetNillableOnTemplate(v *string) *ServerChanConfigUpdate {
	if v != nil {
		_u.SetOnTemplate(*v)
	}
	return _u
}

// SetOffTemplate sets the "off_template" field.
func (_u *ServerChanConfigUpdate) SetOffTemplate(v string) *ServerChanConfigUpdate {
	_u.mutation.SetOffTemplate(v)
	return _u
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (_u *ServerChanConfigUpdate) SetNillableOffTemplate(v *string) *ServerChanConfigUpdate {
	if v != nil {
		_u.SetOffTemplate(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ServerChanConfigUpdate) SetEnabled(v bool) *ServerChanConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ServerChanConfigUpdate) SetNillableEnabled(v *bool) *ServerChanConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ServerChanConfigMutation object of the builder.
func (_u *ServerChanConfigUpdate) Mutation() *ServerChanConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServerChanConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerChanConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServerChanConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerChanConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ServerChanConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(serverchanconfig.Table, serverchanconfig.Columns, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SendKey(); ok {
		_spec.SetField(serverchanconfig.FieldSendKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOnTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.OffTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOffTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(serverchanconfig.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverchanconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServerChanConfigUpdateOne is the builder for updating a single ServerChanConfig entity.
type ServerChanConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServerChanConfigMutation
}

// SetSendKey sets the "send_key" field.
func (_u *ServerChanConfigUpdateOne) SetSendKey(v string) *ServerChanConfigUpdateOne {
	_u.mutation.SetSendKey(v)
	return _u
}

// SetNillableSendKey sets the "send_key" field if the given value is not nil.
func (_u *ServerChanConfigUpdateOne) SetNillableSendKey(v *string) *ServerChanConfigUpdateOne {
	if v != nil {
		_u.SetSendKey(*v)
	}
	return _u
}

// SetOnTemplate sets the "on_template" field.
func (_u *ServerChanConfigUpdateOne) SetOnTemplate(v string) *ServerChanConfigUpdateOne {
	_u.mutation.SetOnTemplate(v)
	return _u
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (_u *ServerChanConfigUpdateOne) SetNillableOnTemplate(v *string) *ServerChanConfigUpdateOne {
	if v != nil {
		_u.SetOnTemplate(*v)
	}
	return _u
}

// SetOffTemplate sets the "off_template" field.
func (_u *ServerChanConfigUpdateOne) SetOffTemplate(v string) *ServerChanConfigUpdateOne {
	_u.mutation.SetOffTemplate(v)
	return _u
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (_u *ServerChanConfigUpdateOne) SetNillableOffTemplate(v *string) *ServerChanConfigUpdateOne {
	if v != nil {
		_u.SetOffTemplate(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ServerChanConfigUpdateOne) SetEnabled(v bool) *ServerChanConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ServerChanConfigUpdateOne) SetNillableEnabled(v *bool) *ServerChanConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ServerChanConfigMutation object of the builder.
func (_u *ServerChanConfigUpdateOne) Mutation() *ServerChanConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServerChanConfigUpdate builder.
func (_u *ServerChanConfigUpdateOne) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServerChanConfigUpdateOne) Select(field string, fields ...string) *ServerChanConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServerChanConfig entity.
func (_u *ServerChanConfigUpdateOne) Save(ctx context.Context) (*ServerChanConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerChanConfigUpdateOne) SaveX(ctx context.Context) *ServerChanConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServerChanConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerChanConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ServerChanConfigUpdateOne) sqlSave(ctx context.Context) (_node *ServerChanConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(serverchanconfig.Table, serverchanconfig.Columns, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServerChanConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serverchanconfig.FieldID)
		for _, f := range fields {
			if !serverchanconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serverchanconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SendKey(); ok {
		_spec.SetField(serverchanconfig.FieldSendKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOnTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.OffTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOffTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(serverchanconfig.FieldEnabled, field.TypeBool, value)
	}
	_node = &ServerChanConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverchanconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
