// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/predicate"
	"cat-led/internal/ent/serverchanconfig"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerChanConfigDelete is the builder for deleting a ServerChanConfig entity.
type ServerChanConfigDelete struct {
	config
	hooks    []Hook
	mutation *ServerChanConfigMutation
}

// Where appends a list predicates to the ServerChanConfigDelete builder.
func (sccd *ServerChanConfigDelete) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigDelete {
	sccd.mutation.Where(ps...)
	return sccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sccd *ServerChanConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sccd.sqlExec, sccd.mutation, sccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sccd *ServerChanConfigDelete) ExecX(ctx context.Context) int {
	n, err := sccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sccd *ServerChanConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(serverchanconfig.Table, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	if ps := sccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sccd.mutation.done = true
	return affected, err
}

// ServerChanConfigDeleteOne is the builder for deleting a single ServerChanConfig entity.
type ServerChanConfigDeleteOne struct {
	sccd *ServerChanConfigDelete
}

// Where appends a list predicates to the ServerChanConfigDelete builder.
func (sccdo *ServerChanConfigDeleteOne) Where(ps ...predicate.ServerChanConfig) *ServerChanConfigDeleteOne {
	sccdo.sccd.mutation.Where(ps...)
	return sccdo
}

// Exec executes the deletion query.
func (sccdo *ServerChanConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := sccdo.sccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{serverchanconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sccdo *ServerChanConfigDeleteOne) ExecX(ctx context.Context) {
	if err := sccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
