// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/serverchanconfig"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServerChanConfigCreate is the builder for creating a ServerChanConfig entity.
type ServerChanConfigCreate struct {
	config
	mutation *ServerChanConfigMutation
	hooks    []Hook
}

// SetSendKey sets the "send_key" field.
func (sccc *ServerChanConfigCreate) SetSendKey(s string) *ServerChanConfigCreate {
	sccc.mutation.SetSendKey(s)
	return sccc
}

// SetOnTemplate sets the "on_template" field.
func (sccc *ServerChanConfigCreate) SetOnTemplate(s string) *ServerChanConfigCreate {
	sccc.mutation.SetOnTemplate(s)
	return sccc
}

// SetNillableOnTemplate sets the "on_template" field if the given value is not nil.
func (sccc *ServerChanConfigCreate) SetNillableOnTemplate(s *string) *ServerChanConfigCreate {
	if s != nil {
		sccc.SetOnTemplate(*s)
	}
	return sccc
}

// SetOffTemplate sets the "off_template" field.
func (sccc *ServerChanConfigCreate) SetOffTemplate(s string) *ServerChanConfigCreate {
	sccc.mutation.SetOffTemplate(s)
	return sccc
}

// SetNillableOffTemplate sets the "off_template" field if the given value is not nil.
func (sccc *ServerChanConfigCreate) SetNillableOffTemplate(s *string) *ServerChanConfigCreate {
	if s != nil {
		sccc.SetOffTemplate(*s)
	}
	return sccc
}

// SetEnabled sets the "enabled" field.
func (sccc *ServerChanConfigCreate) SetEnabled(b bool) *ServerChanConfigCreate {
	sccc.mutation.SetEnabled(b)
	return sccc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (sccc *ServerChanConfigCreate) SetNillableEnabled(b *bool) *ServerChanConfigCreate {
	if b != nil {
		sccc.SetEnabled(*b)
	}
	return sccc
}

// Mutation returns the ServerChanConfigMutation object of the builder.
func (sccc *ServerChanConfigCreate) Mutation() *ServerChanConfigMutation {
	return sccc.mutation
}

// Save creates the ServerChanConfig in the database.
func (sccc *ServerChanConfigCreate) Save(ctx context.Context) (*ServerChanConfig, error) {
	sccc.defaults()
	return withHooks(ctx, sccc.sqlSave, sccc.mutation, sccc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sccc *ServerChanConfigCreate) SaveX(ctx context.Context) *ServerChanConfig {
	v, err := sccc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sccc *ServerChanConfigCreate) Exec(ctx context.Context) error {
	_, err := sccc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccc *ServerChanConfigCreate) ExecX(ctx context.Context) {
	if err := sccc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sccc *ServerChanConfigCreate) defaults() {
	if _, ok := sccc.mutation.OnTemplate(); !ok {
		v := serverchanconfig.DefaultOnTemplate
		sccc.mutation.SetOnTemplate(v)
	}
	if _, ok := sccc.mutation.OffTemplate(); !ok {
		v := serverchanconfig.DefaultOffTemplate
		sccc.mutation.SetOffTemplate(v)
	}
	if _, ok := sccc.mutation.Enabled(); !ok {
		v := serverchanconfig.DefaultEnabled
		sccc.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sccc *ServerChanConfigCreate) check() error {
	if _, ok := sccc.mutation.SendKey(); !ok {
		return &ValidationError{Name: "send_key", err: errors.New(`ent: missing required field "ServerChanConfig.send_key"`)}
	}
	if _, ok := sccc.mutation.OnTemplate(); !ok {
		return &ValidationError{Name: "on_template", err: errors.New(`ent: missing required field "ServerChanConfig.on_template"`)}
	}
	if _, ok := sccc.mutation.OffTemplate(); !ok {
		return &ValidationError{Name: "off_template", err: errors.New(`ent: missing required field "ServerChanConfig.off_template"`)}
	}
	if _, ok := sccc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ServerChanConfig.enabled"`)}
	}
	return nil
}

func (sccc *ServerChanConfigCreate) sqlSave(ctx context.Context) (*ServerChanConfig, error) {
	if err := sccc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sccc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sccc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sccc.mutation.id = &_node.ID
	sccc.mutation.done = true
	return _node, nil
}

func (sccc *ServerChanConfigCreate) createSpec() (*ServerChanConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ServerChanConfig{config: sccc.config}
		_spec = sqlgraph.NewCreateSpec(serverchanconfig.Table, sqlgraph.NewFieldSpec(serverchanconfig.FieldID, field.TypeInt))
	)
	if value, ok := sccc.mutation.SendKey(); ok {
		_spec.SetField(serverchanconfig.FieldSendKey, field.TypeString, value)
		_node.SendKey = value
	}
	if value, ok := sccc.mutation.OnTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOnTemplate, field.TypeString, value)
		_node.OnTemplate = value
	}
	if value, ok := sccc.mutation.OffTemplate(); ok {
		_spec.SetField(serverchanconfig.FieldOffTemplate, field.TypeString, value)
		_node.OffTemplate = value
	}
	if value, ok := sccc.mutation.Enabled(); ok {
		_spec.SetField(serverchanconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// ServerChanConfigCreateBulk is the builder for creating many ServerChanConfig entities in bulk.
type ServerChanConfigCreateBulk struct {
	config
	err      error
	builders []*ServerChanConfigCreate
}

// Save creates the ServerChanConfig entities in the database.
func (scccb *ServerChanConfigCreateBulk) Save(ctx context.Context) ([]*ServerChanConfig, error) {
	if scccb.err != nil {
		return nil, scccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scccb.builders))
	nodes := make([]*ServerChanConfig, len(scccb.builders))
	mutators := make([]Mutator, len(scccb.builders))
	for i := range scccb.builders {
		func(i int, root context.Context) {
			builder := scccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServerChanConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scccb *ServerChanConfigCreateBulk) SaveX(ctx context.Context) []*ServerChanConfig {
	v, err := scccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scccb *ServerChanConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := scccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scccb *ServerChanConfigCreateBulk) ExecX(ctx context.Context) {
	if err := scccb.Exec(ctx); err != nil {
		panic(err)
	}
}
