// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/userpreference"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPreferenceCreate is the builder for creating a UserPreference entity.
type UserPreferenceCreate struct {
	config
	mutation *UserPreferenceMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserPreferenceCreate) SetUserID(v string) *UserPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBulbStyle sets the "bulb_style" field.
func (_c *UserPreferenceCreate) SetBulbStyle(v string) *UserPreferenceCreate {
	_c.mutation.SetBulbStyle(v)
	return _c
}

// SetNillableBulbStyle sets the "bulb_style" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableBulbStyle(v *string) *UserPreferenceCreate {
	if v != nil {
		_c.SetBulbStyle(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPreferenceCreate) SetCreatedAt(v time.Time) *UserPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPreferenceCreate) SetUpdatedAt(v time.Time) *UserPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the UserPreferenceMutation object of the builder.
func (_c *UserPreferenceCreate) Mutation() *UserPreferenceMutation {
	return _c.mutation
}

// Save creates the UserPreference in the database.
func (_c *UserPreferenceCreate) Save(ctx context.Context) (*UserPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPreferenceCreate) SaveX(ctx context.Context) *UserPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPreferenceCreate) defaults() {
	if _, ok := _c.mutation.BulbStyle(); !ok {
		v := userpreference.DefaultBulbStyle
		_c.mutation.SetBulbStyle(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPreferenceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPreference.user_id"`)}
	}
	if _, ok := _c.mutation.BulbStyle(); !ok {
		return &ValidationError{Name: "bulb_style", err: errors.New(`ent: missing required field "UserPreference.bulb_style"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPreference.updated_at"`)}
	}
	return nil
}

func (_c *UserPreferenceCreate) sqlSave(ctx context.Context) (*UserPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPreferenceCreate) createSpec() (*UserPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpreference.Table, sqlgraph.NewFieldSpec(userpreference.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userpreference.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.BulbStyle(); ok {
		_spec.SetField(userpreference.FieldBulbStyle, field.TypeString, value)
		_node.BulbStyle = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserPreferenceCreateBulk is the builder for creating many UserPreference entities in bulk.
type UserPreferenceCreateBulk struct {
	config
	err      error
	builders []*UserPreferenceCreate
}

// Save creates the UserPreference entities in the database.
func (_c *UserPreferenceCreateBulk) Save(ctx context.Context) ([]*UserPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPreferenceCreateBulk) SaveX(ctx context.Context) []*UserPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
