// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cat-led/internal/ent/userpreference"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserPreference is the model entity for the UserPreference schema.
type UserPreference struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 用户ID
	UserID string `json:"user_id,omitempty"`
	// 灯泡样式: classic(经典灯泡), lava(熔岩灯), vintage(老式台灯), liquid(液态光效), lightbulb(灯泡开关), analog(点阵时钟), single-led(表情灯泡), neon-switch(霓虹开关), fox-daynight(狐狸日夜灯)
	BulbStyle string `json:"bulb_style,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPreference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpreference.FieldID:
			values[i] = new(sql.NullInt64)
		case userpreference.FieldUserID, userpreference.FieldBulbStyle:
			values[i] = new(sql.NullString)
		case userpreference.FieldCreatedAt, userpreference.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPreference fields.
func (_m *UserPreference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpreference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userpreference.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case userpreference.FieldBulbStyle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bulb_style", values[i])
			} else if value.Valid {
				_m.BulbStyle = value.String
			}
		case userpreference.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userpreference.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPreference.
// This includes values selected through modifiers, order, etc.
func (_m *UserPreference) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserPreference.
// Note that you need to call UserPreference.Unwrap() before calling this method if this UserPreference
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPreference) Update() *UserPreferenceUpdateOne {
	return NewUserPreferenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserPreference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPreference) Unwrap() *UserPreference {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPreference is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserPreference) String() string {
	var builder strings.Builder
	builder.WriteString("UserPreference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("bulb_style=")
	builder.WriteString(_m.BulbStyle)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserPreferences is a parsable slice of UserPreference.
type UserPreferences []*UserPreference
