// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// ServerChanConfig is the predicate function for serverchanconfig builders.
type ServerChanConfig func(*sql.Selector)
