// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// NtfyConfig is the predicate function for ntfyconfig builders.
type NtfyConfig func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// ServerChanConfig is the predicate function for serverchanconfig builders.
type ServerChanConfig func(*sql.Selector)

// UserPreference is the predicate function for userpreference builders.
type UserPreference func(*sql.Selector)
