// Code generated by ent, DO NOT EDIT.

package userpreference

import (
	"cat-led/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldUserID, v))
}

// BulbStyle applies equality check predicate on the "bulb_style" field. It's identical to BulbStyleEQ.
func BulbStyle(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldBulbStyle, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContainsFold(FieldUserID, v))
}

// BulbStyleEQ applies the EQ predicate on the "bulb_style" field.
func BulbStyleEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldBulbStyle, v))
}

// BulbStyleNEQ applies the NEQ predicate on the "bulb_style" field.
func BulbStyleNEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldBulbStyle, v))
}

// BulbStyleIn applies the In predicate on the "bulb_style" field.
func BulbStyleIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldBulbStyle, vs...))
}

// BulbStyleNotIn applies the NotIn predicate on the "bulb_style" field.
func BulbStyleNotIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldBulbStyle, vs...))
}

// BulbStyleGT applies the GT predicate on the "bulb_style" field.
func BulbStyleGT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldBulbStyle, v))
}

// BulbStyleGTE applies the GTE predicate on the "bulb_style" field.
func BulbStyleGTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldBulbStyle, v))
}

// BulbStyleLT applies the LT predicate on the "bulb_style" field.
func BulbStyleLT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldBulbStyle, v))
}

// BulbStyleLTE applies the LTE predicate on the "bulb_style" field.
func BulbStyleLTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldBulbStyle, v))
}

// BulbStyleContains applies the Contains predicate on the "bulb_style" field.
func BulbStyleContains(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContains(FieldBulbStyle, v))
}

// BulbStyleHasPrefix applies the HasPrefix predicate on the "bulb_style" field.
func BulbStyleHasPrefix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasPrefix(FieldBulbStyle, v))
}

// BulbStyleHasSuffix applies the HasSuffix predicate on the "bulb_style" field.
func BulbStyleHasSuffix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasSuffix(FieldBulbStyle, v))
}

// BulbStyleEqualFold applies the EqualFold predicate on the "bulb_style" field.
func BulbStyleEqualFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEqualFold(FieldBulbStyle, v))
}

// BulbStyleContainsFold applies the ContainsFold predicate on the "bulb_style" field.
func BulbStyleContainsFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContainsFold(FieldBulbStyle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserPreference) predicate.UserPreference {
	return predicate.UserPreference(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserPreference) predicate.UserPreference {
	return predicate.UserPreference(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserPreference) predicate.UserPreference {
	return predicate.UserPreference(sql.NotPredicates(p))
}
