// Code generated by ent, DO NOT EDIT.

package serverchanconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the serverchanconfig type in the database.
	Label = "server_chan_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSendKey holds the string denoting the send_key field in the database.
	FieldSendKey = "send_key"
	// FieldOnTemplate holds the string denoting the on_template field in the database.
	FieldOnTemplate = "on_template"
	// FieldOffTemplate holds the string denoting the off_template field in the database.
	FieldOffTemplate = "off_template"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldEmailEnabled holds the string denoting the email_enabled field in the database.
	FieldEmailEnabled = "email_enabled"
	// FieldEmailURL holds the string denoting the email_url field in the database.
	FieldEmailURL = "email_url"
	// Table holds the table name of the serverchanconfig in the database.
	Table = "server_chan_configs"
)

// Columns holds all SQL columns for serverchanconfig fields.
var Columns = []string{
	FieldID,
	FieldSendKey,
	FieldOnTemplate,
	FieldOffTemplate,
	FieldEnabled,
	FieldEmailEnabled,
	FieldEmailURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOnTemplate holds the default value on creation for the "on_template" field.
	DefaultOnTemplate string
	// DefaultOffTemplate holds the default value on creation for the "off_template" field.
	DefaultOffTemplate string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultEmailEnabled holds the default value on creation for the "email_enabled" field.
	DefaultEmailEnabled bool
	// DefaultEmailURL holds the default value on creation for the "email_url" field.
	DefaultEmailURL string
)

// OrderOption defines the ordering options for the ServerChanConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySendKey orders the results by the send_key field.
func BySendKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSendKey, opts...).ToFunc()
}

// ByOnTemplate orders the results by the on_template field.
func ByOnTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnTemplate, opts...).ToFunc()
}

// ByOffTemplate orders the results by the off_template field.
func ByOffTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOffTemplate, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByEmailEnabled orders the results by the email_enabled field.
func ByEmailEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailEnabled, opts...).ToFunc()
}

// ByEmailURL orders the results by the email_url field.
func ByEmailURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailURL, opts...).ToFunc()
}
