// Code generated by ent, DO NOT EDIT.

package serverchanconfig

import (
	"cat-led/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLTE(FieldID, id))
}

// SendKey applies equality check predicate on the "send_key" field. It's identical to SendKeyEQ.
func SendKey(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldSendKey, v))
}

// OnTemplate applies equality check predicate on the "on_template" field. It's identical to OnTemplateEQ.
func OnTemplate(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldOnTemplate, v))
}

// OffTemplate applies equality check predicate on the "off_template" field. It's identical to OffTemplateEQ.
func OffTemplate(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldOffTemplate, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldEnabled, v))
}

// EmailEnabled applies equality check predicate on the "email_enabled" field. It's identical to EmailEnabledEQ.
func EmailEnabled(v bool) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldEmailEnabled, v))
}

// EmailURL applies equality check predicate on the "email_url" field. It's identical to EmailURLEQ.
func EmailURL(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldEmailURL, v))
}

// SendKeyEQ applies the EQ predicate on the "send_key" field.
func SendKeyEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldSendKey, v))
}

// SendKeyNEQ applies the NEQ predicate on the "send_key" field.
func SendKeyNEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldSendKey, v))
}

// SendKeyIn applies the In predicate on the "send_key" field.
func SendKeyIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldIn(FieldSendKey, vs...))
}

// SendKeyNotIn applies the NotIn predicate on the "send_key" field.
func SendKeyNotIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNotIn(FieldSendKey, vs...))
}

// SendKeyGT applies the GT predicate on the "send_key" field.
func SendKeyGT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGT(FieldSendKey, v))
}

// SendKeyGTE applies the GTE predicate on the "send_key" field.
func SendKeyGTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGTE(FieldSendKey, v))
}

// SendKeyLT applies the LT predicate on the "send_key" field.
func SendKeyLT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLT(FieldSendKey, v))
}

// SendKeyLTE applies the LTE predicate on the "send_key" field.
func SendKeyLTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLTE(FieldSendKey, v))
}

// SendKeyContains applies the Contains predicate on the "send_key" field.
func SendKeyContains(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContains(FieldSendKey, v))
}

// SendKeyHasPrefix applies the HasPrefix predicate on the "send_key" field.
func SendKeyHasPrefix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasPrefix(FieldSendKey, v))
}

// SendKeyHasSuffix applies the HasSuffix predicate on the "send_key" field.
func SendKeyHasSuffix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasSuffix(FieldSendKey, v))
}

// SendKeyEqualFold applies the EqualFold predicate on the "send_key" field.
func SendKeyEqualFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEqualFold(FieldSendKey, v))
}

// SendKeyContainsFold applies the ContainsFold predicate on the "send_key" field.
func SendKeyContainsFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContainsFold(FieldSendKey, v))
}

// OnTemplateEQ applies the EQ predicate on the "on_template" field.
func OnTemplateEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldOnTemplate, v))
}

// OnTemplateNEQ applies the NEQ predicate on the "on_template" field.
func OnTemplateNEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldOnTemplate, v))
}

// OnTemplateIn applies the In predicate on the "on_template" field.
func OnTemplateIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldIn(FieldOnTemplate, vs...))
}

// OnTemplateNotIn applies the NotIn predicate on the "on_template" field.
func OnTemplateNotIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNotIn(FieldOnTemplate, vs...))
}

// OnTemplateGT applies the GT predicate on the "on_template" field.
func OnTemplateGT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGT(FieldOnTemplate, v))
}

// OnTemplateGTE applies the GTE predicate on the "on_template" field.
func OnTemplateGTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGTE(FieldOnTemplate, v))
}

// OnTemplateLT applies the LT predicate on the "on_template" field.
func OnTemplateLT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLT(FieldOnTemplate, v))
}

// OnTemplateLTE applies the LTE predicate on the "on_template" field.
func OnTemplateLTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLTE(FieldOnTemplate, v))
}

// OnTemplateContains applies the Contains predicate on the "on_template" field.
func OnTemplateContains(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContains(FieldOnTemplate, v))
}

// OnTemplateHasPrefix applies the HasPrefix predicate on the "on_template" field.
func OnTemplateHasPrefix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasPrefix(FieldOnTemplate, v))
}

// OnTemplateHasSuffix applies the HasSuffix predicate on the "on_template" field.
func OnTemplateHasSuffix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasSuffix(FieldOnTemplate, v))
}

// OnTemplateEqualFold applies the EqualFold predicate on the "on_template" field.
func OnTemplateEqualFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEqualFold(FieldOnTemplate, v))
}

// OnTemplateContainsFold applies the ContainsFold predicate on the "on_template" field.
func OnTemplateContainsFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContainsFold(FieldOnTemplate, v))
}

// OffTemplateEQ applies the EQ predicate on the "off_template" field.
func OffTemplateEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldOffTemplate, v))
}

// OffTemplateNEQ applies the NEQ predicate on the "off_template" field.
func OffTemplateNEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldOffTemplate, v))
}

// OffTemplateIn applies the In predicate on the "off_template" field.
func OffTemplateIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldIn(FieldOffTemplate, vs...))
}

// OffTemplateNotIn applies the NotIn predicate on the "off_template" field.
func OffTemplateNotIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNotIn(FieldOffTemplate, vs...))
}

// OffTemplateGT applies the GT predicate on the "off_template" field.
func OffTemplateGT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGT(FieldOffTemplate, v))
}

// OffTemplateGTE applies the GTE predicate on the "off_template" field.
func OffTemplateGTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGTE(FieldOffTemplate, v))
}

// OffTemplateLT applies the LT predicate on the "off_template" field.
func OffTemplateLT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLT(FieldOffTemplate, v))
}

// OffTemplateLTE applies the LTE predicate on the "off_template" field.
func OffTemplateLTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLTE(FieldOffTemplate, v))
}

// OffTemplateContains applies the Contains predicate on the "off_template" field.
func OffTemplateContains(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContains(FieldOffTemplate, v))
}

// OffTemplateHasPrefix applies the HasPrefix predicate on the "off_template" field.
func OffTemplateHasPrefix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasPrefix(FieldOffTemplate, v))
}

// OffTemplateHasSuffix applies the HasSuffix predicate on the "off_template" field.
func OffTemplateHasSuffix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasSuffix(FieldOffTemplate, v))
}

// OffTemplateEqualFold applies the EqualFold predicate on the "off_template" field.
func OffTemplateEqualFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEqualFold(FieldOffTemplate, v))
}

// OffTemplateContainsFold applies the ContainsFold predicate on the "off_template" field.
func OffTemplateContainsFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContainsFold(FieldOffTemplate, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldEnabled, v))
}

// EmailEnabledEQ applies the EQ predicate on the "email_enabled" field.
func EmailEnabledEQ(v bool) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldEmailEnabled, v))
}

// EmailEnabledNEQ applies the NEQ predicate on the "email_enabled" field.
func EmailEnabledNEQ(v bool) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldEmailEnabled, v))
}

// EmailURLEQ applies the EQ predicate on the "email_url" field.
func EmailURLEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEQ(FieldEmailURL, v))
}

// EmailURLNEQ applies the NEQ predicate on the "email_url" field.
func EmailURLNEQ(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNEQ(FieldEmailURL, v))
}

// EmailURLIn applies the In predicate on the "email_url" field.
func EmailURLIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldIn(FieldEmailURL, vs...))
}

// EmailURLNotIn applies the NotIn predicate on the "email_url" field.
func EmailURLNotIn(vs ...string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldNotIn(FieldEmailURL, vs...))
}

// EmailURLGT applies the GT predicate on the "email_url" field.
func EmailURLGT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGT(FieldEmailURL, v))
}

// EmailURLGTE applies the GTE predicate on the "email_url" field.
func EmailURLGTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldGTE(FieldEmailURL, v))
}

// EmailURLLT applies the LT predicate on the "email_url" field.
func EmailURLLT(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLT(FieldEmailURL, v))
}

// EmailURLLTE applies the LTE predicate on the "email_url" field.
func EmailURLLTE(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldLTE(FieldEmailURL, v))
}

// EmailURLContains applies the Contains predicate on the "email_url" field.
func EmailURLContains(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContains(FieldEmailURL, v))
}

// EmailURLHasPrefix applies the HasPrefix predicate on the "email_url" field.
func EmailURLHasPrefix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasPrefix(FieldEmailURL, v))
}

// EmailURLHasSuffix applies the HasSuffix predicate on the "email_url" field.
func EmailURLHasSuffix(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldHasSuffix(FieldEmailURL, v))
}

// EmailURLEqualFold applies the EqualFold predicate on the "email_url" field.
func EmailURLEqualFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldEqualFold(FieldEmailURL, v))
}

// EmailURLContainsFold applies the ContainsFold predicate on the "email_url" field.
func EmailURLContainsFold(v string) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.FieldContainsFold(FieldEmailURL, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServerChanConfig) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServerChanConfig) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServerChanConfig) predicate.ServerChanConfig {
	return predicate.ServerChanConfig(sql.NotPredicates(p))
}
