// Code generated by ent, DO NOT EDIT.

package ntfyconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ntfyconfig type in the database.
	Label = "ntfy_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldServerURL holds the string denoting the server_url field in the database.
	FieldServerURL = "server_url"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldOnTemplate holds the string denoting the on_template field in the database.
	FieldOnTemplate = "on_template"
	// FieldOffTemplate holds the string denoting the off_template field in the database.
	FieldOffTemplate = "off_template"
	// Table holds the table name of the ntfyconfig in the database.
	Table = "ntfy_configs"
)

// Columns holds all SQL columns for ntfyconfig fields.
var Columns = []string{
	FieldID,
	FieldEnabled,
	FieldServerURL,
	FieldTopic,
	FieldToken,
	FieldOnTemplate,
	FieldOffTemplate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultServerURL holds the default value on creation for the "server_url" field.
	DefaultServerURL string
	// DefaultTopic holds the default value on creation for the "topic" field.
	DefaultTopic string
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// DefaultOnTemplate holds the default value on creation for the "on_template" field.
	DefaultOnTemplate string
	// DefaultOffTemplate holds the default value on creation for the "off_template" field.
	DefaultOffTemplate string
)

// OrderOption defines the ordering options for the NtfyConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByServerURL orders the results by the server_url field.
func ByServerURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerURL, opts...).ToFunc()
}

// ByTopic orders the results by the topic field.
func ByTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopic, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByOnTemplate orders the results by the on_template field.
func ByOnTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnTemplate, opts...).ToFunc()
}

// ByOffTemplate orders the results by the off_template field.
func ByOffTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOffTemplate, opts...).ToFunc()
}
