// Code generated by ent, DO NOT EDIT.

package ntfyconfig

import (
	"cat-led/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLTE(FieldID, id))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldEnabled, v))
}

// ServerURL applies equality check predicate on the "server_url" field. It's identical to ServerURLEQ.
func ServerURL(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldServerURL, v))
}

// Topic applies equality check predicate on the "topic" field. It's identical to TopicEQ.
func Topic(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldTopic, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldToken, v))
}

// OnTemplate applies equality check predicate on the "on_template" field. It's identical to OnTemplateEQ.
func OnTemplate(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldOnTemplate, v))
}

// OffTemplate applies equality check predicate on the "off_template" field. It's identical to OffTemplateEQ.
func OffTemplate(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldOffTemplate, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldEnabled, v))
}

// ServerURLEQ applies the EQ predicate on the "server_url" field.
func ServerURLEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldServerURL, v))
}

// ServerURLNEQ applies the NEQ predicate on the "server_url" field.
func ServerURLNEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldServerURL, v))
}

// ServerURLIn applies the In predicate on the "server_url" field.
func ServerURLIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldIn(FieldServerURL, vs...))
}

// ServerURLNotIn applies the NotIn predicate on the "server_url" field.
func ServerURLNotIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNotIn(FieldServerURL, vs...))
}

// ServerURLGT applies the GT predicate on the "server_url" field.
func ServerURLGT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGT(FieldServerURL, v))
}

// ServerURLGTE applies the GTE predicate on the "server_url" field.
func ServerURLGTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGTE(FieldServerURL, v))
}

// ServerURLLT applies the LT predicate on the "server_url" field.
func ServerURLLT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLT(FieldServerURL, v))
}

// ServerURLLTE applies the LTE predicate on the "server_url" field.
func ServerURLLTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLTE(FieldServerURL, v))
}

// ServerURLContains applies the Contains predicate on the "server_url" field.
func ServerURLContains(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContains(FieldServerURL, v))
}

// ServerURLHasPrefix applies the HasPrefix predicate on the "server_url" field.
func ServerURLHasPrefix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasPrefix(FieldServerURL, v))
}

// ServerURLHasSuffix applies the HasSuffix predicate on the "server_url" field.
func ServerURLHasSuffix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasSuffix(FieldServerURL, v))
}

// ServerURLEqualFold applies the EqualFold predicate on the "server_url" field.
func ServerURLEqualFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEqualFold(FieldServerURL, v))
}

// ServerURLContainsFold applies the ContainsFold predicate on the "server_url" field.
func ServerURLContainsFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContainsFold(FieldServerURL, v))
}

// TopicEQ applies the EQ predicate on the "topic" field.
func TopicEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldTopic, v))
}

// TopicNEQ applies the NEQ predicate on the "topic" field.
func TopicNEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldTopic, v))
}

// TopicIn applies the In predicate on the "topic" field.
func TopicIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldIn(FieldTopic, vs...))
}

// TopicNotIn applies the NotIn predicate on the "topic" field.
func TopicNotIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNotIn(FieldTopic, vs...))
}

// TopicGT applies the GT predicate on the "topic" field.
func TopicGT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGT(FieldTopic, v))
}

// TopicGTE applies the GTE predicate on the "topic" field.
func TopicGTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGTE(FieldTopic, v))
}

// TopicLT applies the LT predicate on the "topic" field.
func TopicLT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLT(FieldTopic, v))
}

// TopicLTE applies the LTE predicate on the "topic" field.
func TopicLTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLTE(FieldTopic, v))
}

// TopicContains applies the Contains predicate on the "topic" field.
func TopicContains(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContains(FieldTopic, v))
}

// TopicHasPrefix applies the HasPrefix predicate on the "topic" field.
func TopicHasPrefix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasPrefix(FieldTopic, v))
}

// TopicHasSuffix applies the HasSuffix predicate on the "topic" field.
func TopicHasSuffix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasSuffix(FieldTopic, v))
}

// TopicEqualFold applies the EqualFold predicate on the "topic" field.
func TopicEqualFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEqualFold(FieldTopic, v))
}

// TopicContainsFold applies the ContainsFold predicate on the "topic" field.
func TopicContainsFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContainsFold(FieldTopic, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContainsFold(FieldToken, v))
}

// OnTemplateEQ applies the EQ predicate on the "on_template" field.
func OnTemplateEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldOnTemplate, v))
}

// OnTemplateNEQ applies the NEQ predicate on the "on_template" field.
func OnTemplateNEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldOnTemplate, v))
}

// OnTemplateIn applies the In predicate on the "on_template" field.
func OnTemplateIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldIn(FieldOnTemplate, vs...))
}

// OnTemplateNotIn applies the NotIn predicate on the "on_template" field.
func OnTemplateNotIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNotIn(FieldOnTemplate, vs...))
}

// OnTemplateGT applies the GT predicate on the "on_template" field.
func OnTemplateGT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGT(FieldOnTemplate, v))
}

// OnTemplateGTE applies the GTE predicate on the "on_template" field.
func OnTemplateGTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGTE(FieldOnTemplate, v))
}

// OnTemplateLT applies the LT predicate on the "on_template" field.
func OnTemplateLT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLT(FieldOnTemplate, v))
}

// OnTemplateLTE applies the LTE predicate on the "on_template" field.
func OnTemplateLTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLTE(FieldOnTemplate, v))
}

// OnTemplateContains applies the Contains predicate on the "on_template" field.
func OnTemplateContains(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContains(FieldOnTemplate, v))
}

// OnTemplateHasPrefix applies the HasPrefix predicate on the "on_template" field.
func OnTemplateHasPrefix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasPrefix(FieldOnTemplate, v))
}

// OnTemplateHasSuffix applies the HasSuffix predicate on the "on_template" field.
func OnTemplateHasSuffix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasSuffix(FieldOnTemplate, v))
}

// OnTemplateEqualFold applies the EqualFold predicate on the "on_template" field.
func OnTemplateEqualFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEqualFold(FieldOnTemplate, v))
}

// OnTemplateContainsFold applies the ContainsFold predicate on the "on_template" field.
func OnTemplateContainsFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContainsFold(FieldOnTemplate, v))
}

// OffTemplateEQ applies the EQ predicate on the "off_template" field.
func OffTemplateEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEQ(FieldOffTemplate, v))
}

// OffTemplateNEQ applies the NEQ predicate on the "off_template" field.
func OffTemplateNEQ(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNEQ(FieldOffTemplate, v))
}

// OffTemplateIn applies the In predicate on the "off_template" field.
func OffTemplateIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldIn(FieldOffTemplate, vs...))
}

// OffTemplateNotIn applies the NotIn predicate on the "off_template" field.
func OffTemplateNotIn(vs ...string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldNotIn(FieldOffTemplate, vs...))
}

// OffTemplateGT applies the GT predicate on the "off_template" field.
func OffTemplateGT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGT(FieldOffTemplate, v))
}

// OffTemplateGTE applies the GTE predicate on the "off_template" field.
func OffTemplateGTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldGTE(FieldOffTemplate, v))
}

// OffTemplateLT applies the LT predicate on the "off_template" field.
func OffTemplateLT(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLT(FieldOffTemplate, v))
}

// OffTemplateLTE applies the LTE predicate on the "off_template" field.
func OffTemplateLTE(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldLTE(FieldOffTemplate, v))
}

// OffTemplateContains applies the Contains predicate on the "off_template" field.
func OffTemplateContains(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContains(FieldOffTemplate, v))
}

// OffTemplateHasPrefix applies the HasPrefix predicate on the "off_template" field.
func OffTemplateHasPrefix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasPrefix(FieldOffTemplate, v))
}

// OffTemplateHasSuffix applies the HasSuffix predicate on the "off_template" field.
func OffTemplateHasSuffix(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldHasSuffix(FieldOffTemplate, v))
}

// OffTemplateEqualFold applies the EqualFold predicate on the "off_template" field.
func OffTemplateEqualFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldEqualFold(FieldOffTemplate, v))
}

// OffTemplateContainsFold applies the ContainsFold predicate on the "off_template" field.
func OffTemplateContainsFold(v string) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.FieldContainsFold(FieldOffTemplate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NtfyConfig) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NtfyConfig) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NtfyConfig) predicate.NtfyConfig {
	return predicate.NtfyConfig(sql.NotPredicates(p))
}
